### ISSUE TITLE
能详细说明一下，定时任务与自动解锁的流程嘛？

### ISSUE THREAD

**Issue by Khan-KK** [SuperMonster003/Ant-Forest#130]
使用说明不详细，能出定时任务与自动解锁使用说明嘛？

**Comment by SuperMonster003** [comment]
使用说明将在近期完善
目前可尝试根据"配置脚本"的功能及设置提示进行功能测试或探寻

**Comment by zny-yy** [comment]
小米6，自动解锁时，亮屏上滑失败，进入不了输密码状态。

**Comment by SuperMonster003** [comment]
@zny-yy 
尝试在配置工具里 将滑动距离调整到最小 亦即将滑动起点调到最小值 将滑动终点调到最大值

**Comment by 1045302152** [comment]
我也是小米 亮屏之后上滑失败

**Comment by sincegithub** [comment]
> 小米6，自动解锁时，亮屏上滑失败，进入不了输密码状态。

我也是小米6，请问您怎么解决的，调整起点终点没作用

**Comment by Sliller** [comment]
换那种一滑就能进入输密码的锁屏主题，我就是这样解决的，山不转水转。

**Comment by sincegithub** [comment]
> 换那种一滑就能进入输密码的锁屏主题，我就是这样解决的，山不转水转。

比如说哪个主题，我试一下

**Comment by Sliller** [comment]
仿IOS 一滑就进 你自己也可以找找，有很多，自带的不好滑别的都好滑
混搭里面最后改一下就行。













在 2021-01-29 10:21:04，"sincegithub" <notifications@github.com> 写道：

换那种一滑就能进入输密码的锁屏主题，我就是这样解决的，山不转水转。

比如说哪个主题，我试一下

**Comment by SuperMonster003** [comment]
关于定时任务与自动解锁的功能及配置
请参阅配置工具 （ant-forest-setting.js) 中相关功能的 "了解详情" 部分
如仍有疑问 可重新开启此 issue 或新开 isuue
