### ISSUE TITLE
更新再多beta版本也没用，当务之急主要两个需要修复

### ISSUE THREAD

**Issue by lchongxiu** [SuperMonster003/Ant-Forest#185]
更新再多beta版本也没用，当务之急主要两个需要修复：
1、部分机型只能到好友列表，然后就无法进行其他动作，例如VIVO 20 PLUS A；
2、每次执行最多到200-500人就会自动退出，无法完整跑一遍900多好友。
建议小的BUG建议后面修正，先修正大的BUG，让人能先不用人工采集，用机器采集。

**Comment by SuperMonster003** [comment]
第一个参加置顶 issue
第二个推迟 多数人好友数小于 200

当务之急 是尽快完成整体项目的代码重构  
让项目看起来真正像一个像样的项目

另外 欢迎提 PR

注: 推迟≠无视

**Comment by SuperMonster003** [comment]
好友数量多的时候列表卡顿问题将在后期逐步完成优化
感谢支持

**Comment by SuperMonster003** [comment]
v2.1.0 已增加逛一逛按钮采集方案  可以一定程度避免排行榜的遗留问题
如新方案依然存在问题  可重新开 issue 反馈
此 issue 暂时关闭
