### ISSUE TITLE
偶尔出现好友列表滑不动

### ISSUE THREAD

**Issue by youaaaaa** [SuperMonster003/Ant-Forest#236]

**Comment by youaaaaa** [comment]
150左右好友, 
如果有滑不动,位置一般卡在90+   120+的某个好友重复点击却没上滑

**Comment by youaaaaa** [comment]
![0be0ff4d86ebb5b61cdc63ad148f711d](https://user-images.githubusercontent.com/57583951/71760999-81a80880-2f00-11ea-82c5-357277914949.gif)

**Comment by ggyy8850** [comment]
是的，经常出现此情况

**Comment by SuperMonster003** [comment]
v1.9.17已经尝试修复此问题
但不能保证修复效果
因为暂时还未能确定问题根源

如果问题浮现
请反馈时附上排行榜滑动的参数
包括滑动间隔 滑动时长

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Ant-Forest/issues/149#issuecomment-775706986
