### ISSUE TITLE
功能建议: 建议修改查看更多好友功能

### ISSUE THREAD

**Issue by lchongxiu-beijing** [SuperMonster003/Ant-Forest#277]
我有900多好友，用作者程序基本在500-650之间就会无法继续下去，但另外一个作者的程序可以跑完全部好友。我查看了对方的源代码，提供相关一部分内容供作者参考，看是否有用：

        let canScrollDown = true
        if ((lastCheckedFriend >= totalValidLength - 1 || _commonFunctions.getQueueDistinctSize(distinctQueue) <= 3) && this.all_loaded === false) {
          canScrollDown = false
          this.usedList = true
          this.condition.signal()
          let newValidList = null
          let tryReloadCount = 0
          do {
            if (newValidList !== null) {
              debugInfo('获取到的长度无变化，上下滑动触发加载')
              tryReloadCount++
              if (tryReloadCount === 3) {
                // 尝试重新出发加载达到三次，上划一页
                scrollUp()
              } else if (tryReloadCount >= 5) {
                // 多次出发失败，直接返回重新开始
                errorInfo('触发加载失败，重新开始')
                if (screen !== null) {
                  screen.recycle()
                }
                return true
              }
              automator.scrollUpAndDown()
              this.usedList = true
            }

**Comment by SuperMonster003** [comment]
感谢提供建议与方案
庞大数量好友列表滑动问题将在v1.9.17后集中处理
注: 下一版为v.1.9.16 暂不会对此问题做出优化

**Comment by SuperMonster003** [comment]
v2.1.0 已增加逛一逛按钮采集方案 可以一定程度避免排行榜的遗留问题
如新方案依然存在问题 可重新开 issue 反馈
此 issue 暂时关闭
