### ISSUE TITLE
Bug反馈: [ 好友排行榜到两三百人就卡住 ]

### ISSUE THREAD

**Issue by mymizang** [SuperMonster003/Ant-Forest#304]
**问题描述**
前面的一切正常，但是到240-280好友左右就卡死，即便延迟反应时间和点击时间仍旧如此。

**日志截图**
https://i.loli.net/2020/05/02/nqC71BifGskNA8p.png

**软件硬件信息**
操作系统: [ 如: 安卓8.1.0 ]
设备型号: [ 如: 360N7 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.18 ]

**Comment by ljaist** [comment]
我目前400多好友，到300左右会慢但还没卡死。只是底部识别有点困难

**Comment by SuperMonster003** [comment]
v2.1.0 已增加逛一逛按钮采集方案 可以一定程度避免排行榜的遗留问题
如新方案依然存在问题 可重新开 issue 反馈
此 issue 暂时关闭
