### ISSUE TITLE
黑名单问题

### ISSUE THREAD

**Issue by Qingtian-creat** [SuperMonster003/Ant-Forest#369]
黑名单识别能不能在排行榜就直接识别而不进入黑名单好友的森林页面？
  现在的识别模式感觉很耗费时间，每次识别都得进入黑名单好友的森林页面然后退出，而且排行榜样本复查的时候还是会再次进入，这样大大增加了脚本的运行时间

**Comment by xu-liyan** [comment]
我也发现了同样的问题，希望可以优化一下黑名单逻辑。

**Comment by ljaist** [comment]
能力罩黑名单有识别失败的情况，在设置里部分有罩的好友不在单里

**Comment by TonyJiangWJ** [comment]
图像分析模式无法获取到控件信息的，只能进到好友首页才能得到相应的好友名称，列表中除非使用OCR识别，否则不能实现。另外即便用了OCR，因为网络延迟和识别准确率的问题，还不如直接进到好友页面获取来的快。

**Comment by SuperMonster003** [comment]
@TonyJiangWJ 
---
感谢 Tony 的解答
😄 
---
---
@ljaist 下一版 `v1.9.23` 将黑名单信息采集相关代码做一些轻微调整
---
新版本发布后 如依然出现识别问题 可发布新 Issue 反馈
---
---
@Qingtian-creat @xu-liyan 
---
黑名单问题和排行榜好友数量多于 200 的执行效率问题
一直是当前项目的棘手问题
而上述两个问题彼此还是矛盾的
保证多好友不卡顿就要牺牲黑名单检测效率
---
当前项目的用户多数是好友数量不足 100 的
上述两个问题均没有明显影响
而黑名单数量很多的用户 往往好友数量也很多 (多于200)
这些用户会同时受上述两个问题的影响
所以如果有用户发现项目的黑名单识别效率提升了
则他同时有大概率发现排行榜滑动效率变低了
考虑到排行榜滑动是所有人必定会执行的
因此着力提升排行榜滑动效率 而牺牲黑名单识别效率
---
未来可能根据实际情况还原以前的"图像识别/控件分析"识别模式供用户选择切换
但可能性不大

**Comment by SuperMonster003** [comment]
排行榜列表对于黑名单好友将不再考虑做识别
此 issue 暂时关闭并增加 "无法完成" 标签
