### ISSUE TITLE
Bug反馈: [ 列表底部控件图片模板异常导致排行榜提前结束样本采集 ] (Edited)

### ISSUE THREAD

**Issue by xy3217991** [SuperMonster003/Ant-Forest#377]
**问题描述**
支付宝好友界面只下翻一次，界面能显示十几个好友，收完能量就自动结束了（我有六十多个好友），导致后面好友的能量无法收取

**日志截图**

**软件硬件信息**
操作系统: [ MIUI12]
设备型号: [ 小米6 ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.22 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by xiaoheiyn** [comment]
我也是这样

**Comment by xy3217991** [comment]
> 我也是这样

经过多次调试，我查到了我的原因，在设置里面---帮收功能---排行榜样本采集---列表底部控件图片模板，查看模板后发现原本的“没有更多了”变成全黑图片，将其删除后重新生成模板，便可以成功下滑好友列表并收集能量。

**Comment by xiaoheiyn** [comment]
> > 我也是这样
> 
> 经过多次调试，我查到了我的原因，在设置里面---帮收功能---排行榜样本采集---列表底部控件图片模板，查看模板后发现原本的“没有更多了”变成全黑图片，将其删除后重新生成模板，便可以成功下滑好友列表并收集能量。

感谢大佬，问题解决了

**Comment by Azhao1993** [comment]
> > 我也是这样
> 
> 经过多次调试，我查到了我的原因，在设置里面---帮收功能---排行榜样本采集---列表底部控件图片模板，查看模板后发现原本的“没有更多了”变成全黑图片，将其删除后重新生成模板，便可以成功下滑好友列表并收集能量。

有用

**Comment by leestars** [comment]
删除之后可以，但是运行一次没有生成新的模版，怎么回事？

**Comment by ayuanet** [comment]
666,解决了

**Comment by weitemi** [comment]
> > 我也是这样
> 
> 经过多次调试，我查到了我的原因，在设置里面---帮收功能---排行榜样本采集---列表底部控件图片模板，查看模板后发现原本的“没有更多了”变成全黑图片，将其删除后重新生成模板，便可以成功下滑好友列表并收集能量。

是的 我也是这样的，我用的是三星S9。需要删除生成的模板。

**Comment by leestars** [comment]
过一段时间后 又自动生成了一张黑色的图片 今天刚发现 删除就可以了 我的是三星s8 @SuperMonster003

**Comment by Santo-wiar** [comment]
可是删除了  只能用两三次 马上又生成纯黑的异常模板了...

**Comment by SuperMonster003** [comment]
v1.9.23 将进一步完善关于列表底部控件图片模板的代码逻辑并尝试修复上述问题

**Comment by ljaist** [comment]
我的列表底部有几个没开通森林的好友，导致底部无法识别

**Comment by SuperMonster003** [comment]
v2.0.1 删除了排行榜底部控件图片模板相关的代码
