### ISSUE TITLE
建议优化：蚂蚁森林新增搜一搜功能，可以不用频繁返回排行榜页面去访问下一位可偷取好友了

### ISSUE THREAD

**Issue by rhee2333** [SuperMonster003/Ant-Forest#391]

**Comment by wtus** [comment]
逛一逛，不是搜一搜

**Comment by AlbertLinstan** [comment]
期待，这样效率就会更高了。支持作者。

**Comment by zhu086** [comment]
期待中

**Comment by SuperMonster003** [comment]
v2.1.0 已增加逛一逛按钮采集方案
如新方案存在问题 可继续反馈

**Comment by NonoHh** [comment]
> v2.1.0 已增加逛一逛按钮采集方案
> 如新方案存在问题 可继续反馈

作者您好，202105513后，每日首次逛一逛到达没有能量可收的界面时，会弹出来推荐去玩拯救能量雨的活动，脚本会卡住。

**Comment by SuperMonster003** [comment]
@NonoHh
`v2.1.1` 已尝试修复上述问题
试用后如果问题依然存在 可继续反馈

**Comment by NonoHh** [comment]
@SuperMonster003 谢谢作者，今天0点体验后如有问题我再继续反馈。
