### ISSUE TITLE
华为nova6升级MIUI 11无法解锁

### ISSUE THREAD

**Issue by ZipperLi** [SuperMonster003/Ant-Forest#411]
老哥，请问下，华为新系统MIUI 11升级了过后，就定时任务自动解锁总是无效的，请问这个该咋个解决呢。。。。。谢谢老哥。

**Comment by SuperMonster003** [comment]
可尝试运行项目Tools文件夹里的Inspect_Lock_Screen_Layout.js 并按提示提供解锁布局信息

**Comment by ZipperLi** [comment]
老哥你好，布局信息和文件都在这里了。麻烦了哈。谢谢。
[!Debug_Info.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/5636285/Debug_Info.zip)

**Comment by SuperMonster003** [comment]
[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/5643261/MODULE_UNLOCK.zip)
可尝试将上述模块替换现有模块
然后测试解锁功能

如问题复现 请描述异常现象并提供解锁过程日志 (需开启项目的开发者测试模式 或 使用代码进行解锁 代码详见解锁模块的JSDoc)

**Comment by ZipperLi** [comment]
好的，我试试，谢谢哈。

**Comment by ZipperLi** [comment]
老哥，我试过了，密码问题已经得到了解决。但是好像定时任务来解锁是有会失败的。。不知道这个我应该去咋个解决呢。谢谢。

**Comment by SuperMonster003** [comment]
提供解锁失败的日志并详述解锁失败过程

**Comment by ZipperLi** [comment]
![Screenshot_20201214_110323_org autojs autojs](https://user-images.githubusercontent.com/38458546/102035696-059a8e00-3dfc-11eb-902f-61f4fdab2c4b.jpg)
老哥，不好意思，这两天有点忙，今天截的图，麻烦你看下嘛，我设定的定时任务为早上7点10分、7点20，7点30，但是这个时间就看我什么时候点亮屏幕了，如果是7点50或者8点，那么久会到那个时候运行，。在定时任务执行的日志在autojs里面没有看到，不知道还有哪里能够提供给你，谢谢。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Ant-Forest/issues/134
