### ISSUE TITLE
Bug反馈: [ 突然不能使用 ]

### ISSUE THREAD

**Issue by pxxiao-hz** [SuperMonster003/Ant-Forest#412]
老哥，这个如何解决，上午好好的，下午突然不能用了，报错信息如下：

Auto.js：错误：TypeError：
cannot call method “trim" of undefined(....../Ant_Forest_Launcher.js#652)

**Comment by pxxiao-hz** [comment]
删除trim即可使用。
另外，为了提高效率，下一版是否可以使用”找能量“这一功能。期待下一次更新。

**Comment by pxxiao-hz** [comment]
支付宝再次更新，出现“提醒好友收能量，收取后分你一半”，然后脚本无限循环下去了...

**Comment by SuperMonster003** [comment]
报错在 v2.0.1 已修复
另外蚂蚁森林目前的版本已更改了 "提醒守护功能" 的行为逻辑
不会影响脚本正常运行
