### ISSUE TITLE
已经完全按照教程中的位置放置文件，仍提示“模块缺失或路径错误”

### ISSUE THREAD

**Issue by geniebullfinch** [SuperMonster003/Ant-Forest#415]
**问题描述**
已经完全按照教程中的位置放置文件，仍提示“模块缺失或路径错误”，在多次尝试后，终于有一次使脚本显示运行，但最后提示错误，让我复制错误反馈如下：

Version: 461
Android: 29
android.os.TransactionTooLargeException: data parcel size 1706556 bytes
java.lang.RuntimeException:android.os.TransactionTooLargeException: data parcel size 1706556 bytes
android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
......
Caused by:
android.os.TransactionTooLargeException:data parcel size 1706556 bytes
android.os.BinderProxy.transactNative(Native Method)
android.os.BinderProxy.transact(BinderProxy.java:532)
android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4561)
android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
android.os.Handler.handleCallback(Handler.java:900)
android.os.Handler.dispatchMessage(Handler.java:103)
android.os.Looper.loop(Looper.java:219)
android.app.ActivityThread.main(ActivityThread.java:8347)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**日志截图**
不知道如何上传截图T_T

**软件硬件信息**
操作系统: [ EMUI10.1.0/ 安卓10 ]
设备型号: [ 华为P30 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
----
使用 GitHub 上传图片
----

- 移动端:
点击输入框上方的 "上传图片" 图标 然后选择图片文件
- PC端: 
点击输入框下方的 "Attach files by dragging & dropping, selecting or pasting them." 然后选择图片
或直接将图片从资源管理器拖拽至输入框

---
关于此 issue
---

v2.0.1 增加了项目部署工具
使用部署工具可直接将项目自动部署到设备本地
部署完成后 默认会在 Auto.js 的主页出现 Ant-Forest-003 文件夹
(如未出现 可能需要在 Auto.js 页面下拉刷新)
进入文件夹后可按原始运行方式运行 launcher 和 settings
也可点击项目目录顶部的运行按钮运行项目 (与运行 launcher 效果相同)

android.os.TransactionTooLargeException
出现上述异常时 运行的是 launcher 还是 settings
