### ISSUE TITLE
Bug反馈: [进入好友森林超时]

### ISSUE THREAD

**Issue by frank142857** [SuperMonster003/Ant-Forest#416]
**问题描述**
无法检测进入好友页面状态，提示“进入好友森林超时”。

**日志截图**
![image](https://user-images.githubusercontent.com/35618259/105568986-d0794800-5d78-11eb-954f-b809fb983dfa.png)

**软件硬件信息**
操作系统: [ 如: 安卓8.1 ]
设备型号: [ 如: 魅族16th]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.25 ]

**Comment by dacs6** [comment]
我也是这个情况，可能和蚂蚁森林版本更新有关。
进入好友页面后，需要手工点“点击展开好友动态”，程序才能自动收取能量。而之前好友状态缺省就是展开的。

**Comment by yzliufujin** [comment]
`进入好友页面后，需要手工点“点击展开好友动态”，程序才能自动收取能量。而之前好友状态缺省就是展开的。`
我也发现了这个问题。

**Comment by SuperMonster003** [comment]
预计不晚于周日晚前修复上述问题
目前可考虑采用如下临时方案

```diff
> Ant_Forest_Launcher.js:1306

- /赠送的\s?\d+g\s?.*能量|点击加载更多/.source
+ /赠送的\s?\d+g\s?.*能量|点击加载更多|点击展开好友动态/.source
```

**Comment by SuperMonster003** [comment]
新版本未能如期完成开发
目前可参考上述临时方案
新版本将在近期尽快发布

**Comment by lixifei12138** [comment]
请问临时策略怎么使用呀

**Comment by Xm798** [comment]
> 请问临时策略怎么使用呀

编辑Ant_Forest_Launcher.js，将第1306行 `/赠送的\s?\d+g\s?.*能量|点击加载更多/.source` 修改为`/赠送的\s?\d+g\s?.*能量|点击加载更多|点击展开好友动态/.source`

**Comment by lixifei12138** [comment]
> > 请问临时策略怎么使用呀
> 
> 编辑Ant_Forest_Launcher.js，将第1306行 `/赠送的\s?\d+g\s?.*能量|点击加载更多/.source` 修改为`/赠送的\s?\d+g\s?.*能量|点击加载更多|点击展开好友动态/.source` @lixifei12138

谢谢

**Comment by SuperMonster003** [comment]
此问题已于 v2.0.1 解决
如果问题复现 可重新反馈
此 issue 暂时关闭
