### ISSUE TITLE
Bug反馈: 从昨天开始一到可收取的能量球那个页面，就停住了，不能自动收取自己的能量和好友的能量

### ISSUE THREAD

**Issue by zhu086** [SuperMonster003/Ant-Forest#417]
**问题描述**
今天终于看到作者回复了，能量页不会自动收取能量，停住了

**日志截图**
![QQ图片20210123193452](https://user-images.githubusercontent.com/67412456/105577132-c07e5a00-5db2-11eb-99d6-0475086cbe66.jpg)
![QQ图片20210123193456](https://user-images.githubusercontent.com/67412456/105577180-ead01780-5db2-11eb-9dc4-73497e1d4173.jpg)

**软件硬件信息**
操作系统: [ 如: 安卓10 ]
设备型号: [ 如: 华为p30 pro ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.25]

**Comment by RobbieDragon233** [comment]
应该是和#416一样的问题吧，可以参看临时解法

**Comment by fauthor** [comment]
我的也是，可以正常进入好友界面，进去后就停住了

**Comment by wshao1279** [comment]
原因是没有自动展开好友动态  展开好友动态后自动收取  请求解决 谢谢

**Comment by wshao1279** [comment]
![image](https://user-images.githubusercontent.com/59464124/105931727-ae3c3e80-6086-11eb-98c9-abf17ca6bfbe.png)

**Comment by wshao1279** [comment]
已解决 感谢
/赠送的\s?\d+g\s?.*能量|点击加载更多|点击展开好友动态/.source

**Comment by hdb66** [comment]
> 已解决感谢
> /给予礼物的\ s？\ d + g \ s？。*能量|点击加载更多|点击展开好友动态/.source

您好，请问这行代码要怎么修改呢？

**Comment by lisz032** [comment]
> > 已解决感谢
> > /给予礼物的\ s？\ d + g \ s？。*能量|点击加载更多|点击展开好友动态/.source
> 
> 您好，请问这行代码要怎么修改呢？

修改Ant_Forest_Launcher那个文件，在里面搜索**“赠送”**然后把**“/赠送的\s?\d+g\s?.*能量|点击加载更多/.source”**修改成**“/给予礼物的\ s？\ d + g \ s？。*能量|点击加载更多|点击展开好友动态/.source”**完美解决

**Comment by hdb66** [comment]
好的，非常感谢您的帮忙，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperMonster003/Ant-Forest"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月30日(星期六) 中午11:43
收件人:&nbsp;"SuperMonster003/Ant-Forest"<Ant-Forest@noreply.github.com&gt;;
抄送:&nbsp;"?????"<895206760@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [SuperMonster003/Ant-Forest] Bug反馈: 从昨天开始一到可收取的能量球那个页面，就停住了，不能自动收取自己的能量和好友的能量 (#417)





   
已解决感谢
 /给予礼物的\ s？\ d + g \ s？。*能量|点击加载更多|点击展开好友动态/.source
  
您好，请问这行代码要怎么修改呢？
  
修改Ant_Forest_Launcher那个文件，在里面搜索**“赠送”然后把“/赠送的\s?\d+g\s?.*能量|点击加载更多/.source”修改成“/给予礼物的\ s？\ d + g \ s？。*能量|点击加载更多|点击展开好友动态/.source”**完美解决

**Comment by meetinnet** [comment]
照着改了，为什么不生效，到了那个收取能量的界面，之前是卡住，改了之后直接就返回了，也没收取能量。

**Comment by wshao1279** [comment]
今天又出现了之前那个问题    修改了1306行的代码  还是不能自动收能量，必须手动点开“点击展开好友动态”，能不能加一行代码，在收能量之前执行点击展开好友动态”谢谢
才行在2，021年2月1日 09:10，meetinnet<notifications@github.com> 写道：

照着改了，为什么不生效，到了那个收取能量的界面，之前是卡住，改了之后直接就返回了，也没收取能量。

**Comment by RobbieDragon233** [comment]
> 今天又出现了之前那个问题 修改了1306行的代码 还是不能自动收能量，必须手动点开“点击展开好友动态”，能不能加一行代码，在收能量之前执行点击展开好友动态”谢谢 才行在2，021年2月1日 09:10，meetinnet<notifications@github.com> 写道： 照着改了，为什么不生效，到了那个收取能量的界面，之前是卡住，改了之后直接就返回了，也没收取能量。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

支付宝界面有变化了啊 只有等作者更新程序了

**Comment by keniji** [comment]
> > 今天又出现了之前那个问题 修改了1306行的代码 还是不能自动收能量，必须手动点开“点击展开好友动态”，能不能加一行代码，在收能量之前执行点击展开好友动态”谢谢 才行在2，021年2月1日 09:10，meetinnet[notifications@github.com](mailto:notifications@github.com) 写道： 照着改了，为什么不生效，到了那个收取能量的界面，之前是卡住，改了之后直接就返回了，也没收取能量。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 支付宝界面有变化了啊 只有等作者更新程序了

看来不是我一个人啊，怎么反馈issue的人这么少

**Comment by wshao1279** [comment]
第 5483 行
将 _ready() && 给注释掉
修改前:
_ready() && $$ link(_click).$(_stat);
修改后:
/* _ready() && */ $$ link(_click).$(_stat);


OK了


在2021年2月3日 07:53，keniji<notifications@github.com> 写道：

今天又出现了之前那个问题 修改了1306行的代码 还是不能自动收能量，必须手动点开“点击展开好友动态”，能不能加一行代码，在收能量之前执行点击展开好友动态”谢谢 才行在2，021年2月1日 09:10，meetinnetnotifications@github.com 写道： 照着改了，为什么不生效，到了那个收取能量的界面，之前是卡住，改了之后直接就返回了，也没收取能量。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

支付宝界面有变化了啊 只有等作者更新程序了

看来不是我一个人啊，怎么反馈issue的人这么少

**Comment by dotama** [comment]
1308行 in_page_rex_spe: /点击展开好友动态|今天|昨天|\d{2}-\d{2}/, // > cY(0.85)

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Ant-Forest/issues/416
