### ISSUE TITLE
Bug反馈: [ 无法正常运行收能量功能]

### ISSUE THREAD

**Issue by LeonSUST** [SuperMonster003/Ant-Forest#418]
**问题描述**
启动项目后，无法进行正常的自收能量和收他人能量的工作

**日志截图**
无截图，就是不允许  长时间后自动息屏了

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 荣耀30PRO ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.25 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by dotama** [comment]
1308行 in_page_rex_spe: /点击展开好友动态|今天|昨天|\d{2}-\d{2}/, // > cY(0.85)

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Ant-Forest/issues/416
