### ISSUE TITLE
Bug反馈: 1.数据统计初始化失败 2.定时任务不受时间范围控制

### ISSUE THREAD

**Issue by Xm798** [SuperMonster003/Ant-Forest#419]
**问题1描述**
数据统计初始化失败，从6:50执行到8:00一直是该错误。

**日志截图**
![Screenshot_2021-02-01-08-06-33-494_org.autojs.autojs_Mosaic_8_8_41.jpg](https://user-images.githubusercontent.com/48074861/106402534-db149b00-6464-11eb-91de-28e0bcda38d4.jpg)
![Screenshot_2021-02-01-08-06-43-712_org.autojs.autojs_Mosaic_8_9_20.jpg](https://user-images.githubusercontent.com/48074861/106402535-de0f8b80-6464-11eb-8b77-e92d1d1dba6d.jpg)

**问题2描述**
定时任务管理失效。
设置自动任务在6:50-7:20之间有效，但是八点多仍然试图自动运行任务。

**日志截图**
![Screenshot_2021-02-01-08-07-02-463_org.autojs.autojs.jpg](https://user-images.githubusercontent.com/48074861/106402657-79a0fc00-6465-11eb-8936-f36a9ca31a56.jpg)
![Screenshot_2021-02-01-08-06-06-919_org.autojs.autojs_Mosaic_8_14_46.jpg](https://user-images.githubusercontent.com/48074861/106402687-a48b5000-6465-11eb-8ed5-dda0044929fc.jpg)

**软件硬件信息**
操作系统: [ MIUI 12.5 Android 11 ]
设备型号: [ MI 10 Pro ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.25 ]

**Comment by wen704** [comment]
临时修改方案(修改后可以收能量,但是无法正确统计,即日志中看不到具体收获的能量):
[url=https://sm.ms/image/Ls9MjHry42Q3XFk][img]https://i.loli.net/2021/02/01/Ls9MjHry42Q3XFk.png[/img][/url]
[url=https://sm.ms/image/DIOeR8HUykfmSab][img]https://i.loli.net/2021/02/01/DIOeR8HUykfmSab.png[/img][/url]

**Comment by Xm798** [comment]
> 临时修改方案(修改后可以收能量,但是无法正确统计,即日志中看不到具体收获的能量):
> ![Ant_Forest_Launcher修改前代码](https://user-images.githubusercontent.com/20456050/106410152-289d0200-647d-11eb-9bfd-ddcca76de2f8.png)
> ![Ant_Forest_Launcher修改后代码](https://user-images.githubusercontent.com/20456050/106410173-35215a80-647d-11eb-82bb-11dd94b85a7c.png)
> ![Ant_Forest_Launcher修改前代码](https://i.loli.net/2021/02/01/Ls9MjHry42Q3XFk.png)
> ![Ant_Forest_Launcher修改后代码](https://i.loli.net/2021/02/01/DIOeR8HUykfmSab.png)

我尝试修改一下，谢谢！！

**Comment by crb8331** [comment]
2楼的师傅能不能把需要修改代码发出来，我这里图片显示无法打开，谢谢了。

**Comment by wen704** [comment]
@crb8331 
其实我贴了一个国内能加载的图床的...不知道为啥你那显示不了
具体修改就是 Ant_Forest_Launcher.js 第 5483 行
将 _ready() && 给注释掉
修改前:
_ready() && $$ link(_click).$(_stat);
修改后:
/* _ready() && */ $$ link(_click).$(_stat);
[Ant_Forest_Launcher修改前代码](https://user-images.githubusercontent.com/20456050/106410152-289d0200-647d-11eb-9bfd-ddcca76de2f8.png)
[Ant_Forest_Launcher修改后代码](https://user-images.githubusercontent.com/20456050/106410173-35215a80-647d-11eb-82bb-11dd94b85a7c.png)
[Ant_Forest_Launcher修改前代码](https://i.loli.net/2021/02/01/Ls9MjHry42Q3XFk.png)
[Ant_Forest_Launcher修改后代码](https://i.loli.net/2021/02/01/DIOeR8HUykfmSab.png)

**Comment by crb8331** [comment]
刚刚忙完工作，我把5483行改了一下，确实正常了，谢谢你大神，原理吧我是真不懂，谢谢了（wen704）。

**Comment by wyfang** [comment]
> @crb8331
> 其实我贴了一个国内能加载的图床的...不知道为啥你那显示不了
> 后2个链接是国内能访问的图床地址,前2个是github自带的图床地址
> 具体修改就是 Ant_Forest_Launcher.js 第 5483 行
> 将 _ready() && 给注释掉
> 修改前:
> _ready() && $$ link(_click).$(_stat);
> 修改后:
> /* _ready() && */ $$ link(_click).$(_stat);
> [Ant_Forest_Launcher修改前代码](https://user-images.githubusercontent.com/20456050/106410152-289d0200-647d-11eb-9bfd-ddcca76de2f8.png)
> [Ant_Forest_Launcher修改后代码](https://user-images.githubusercontent.com/20456050/106410173-35215a80-647d-11eb-82bb-11dd94b85a7c.png)
> [Ant_Forest_Launcher修改前代码](https://i.loli.net/2021/02/01/Ls9MjHry42Q3XFk.png)
> [Ant_Forest_Launcher修改后代码](https://i.loli.net/2021/02/01/DIOeR8HUykfmSab.png)

不行啊，修改后运行直接报错：12:12:53.890/E: missing ; before statement (/storage/emulated/0/autojs/Ant-Forest-1.9.25/Ant_Forest_Launcher.js#5483) missing ; before statement

**Comment by Xm798** [comment]
> > @crb8331
> > 其实我贴了一个国内能加载的图床的...不知道为啥你那显示不了
> > 后2个链接是国内能访问的图床地址,前2个是github自带的图床地址
> > 具体修改就是 Ant_Forest_Launcher.js 第 5483 行
> > 将 _ready() && 给注释掉
> > 修改前:
> > _ready() && $$ link(_click).$(_stat);
> > 修改后:
> > /* _ready() && */ $$ link(_click).$(_stat);
> > [Ant_Forest_Launcher修改前代码](https://user-images.githubusercontent.com/20456050/106410152-289d0200-647d-11eb-9bfd-ddcca76de2f8.png)
> > [Ant_Forest_Launcher修改后代码](https://user-images.githubusercontent.com/20456050/106410173-35215a80-647d-11eb-82bb-11dd94b85a7c.png)
> > [Ant_Forest_Launcher修改前代码](https://i.loli.net/2021/02/01/Ls9MjHry42Q3XFk.png)
> > [Ant_Forest_Launcher修改后代码](https://i.loli.net/2021/02/01/DIOeR8HUykfmSab.png)
> 
> 不行啊，修改后运行直接报错：12:12:53.890/E: missing ; before statement (/storage/emulated/0/autojs/Ant-Forest-1.9.25/Ant_Forest_Launcher.js#5483) missing ; before statement

`/* _ready() && */$$ link(_click).$(_stat);`

$$前多了一个空格

**Comment by wyfang** [comment]
> > > @crb8331
> > > 其实我贴了一个国内能加载的图床的...不知道为啥你那显示不了
> > > 后2个链接是国内能访问的图床地址,前2个是github自带的图床地址
> > > 具体修改就是 Ant_Forest_Launcher.js 第 5483 行
> > > 将 _ready() && 给注释掉
> > > 修改前:
> > > _ready() && $$ link(_click).$(_stat);
> > > 修改后:
> > > /* _ready() && */ $$ link(_click).$(_stat);
> > > [Ant_Forest_Launcher修改前代码](https://user-images.githubusercontent.com/20456050/106410152-289d0200-647d-11eb-9bfd-ddcca76de2f8.png)
> > > [Ant_Forest_Launcher修改后代码](https://user-images.githubusercontent.com/20456050/106410173-35215a80-647d-11eb-82bb-11dd94b85a7c.png)
> > > [Ant_Forest_Launcher修改前代码](https://i.loli.net/2021/02/01/Ls9MjHry42Q3XFk.png)
> > > [Ant_Forest_Launcher修改后代码](https://i.loli.net/2021/02/01/DIOeR8HUykfmSab.png)
> > 
> > 
> > 不行啊，修改后运行直接报错：12:12:53.890/E: missing ; before statement (/storage/emulated/0/autojs/Ant-Forest-1.9.25/Ant_Forest_Launcher.js#5483) missing ; before statement
> 
> `/* _ready() && */ $$link(_click).$(_stat);`
> 
> $$后面多了一个空格

还是不行：
16:55:23.178/E: unterminated regular expression literal (/storage/emulated/0/autojs/Ant-Forest-1.9.25/Ant_Forest_Launcher.js#6881)
unterminated regular expression literal

**Comment by wshao1279** [comment]
修改完 OK了

**Comment by SuperMonster003** [comment]
v2.0.1 已发布
如上述两个问题复现
可继续反馈
此 issue 暂时保留 14 天

**Comment by Xm798** [comment]
> v2.0.1 已发布
> 如上述两个问题复现
> 可继续反馈
> 此 issue 暂时保留 14 天

作者大大辛苦啦！！
