### ISSUE TITLE
Bug反馈: 已按前面方法修改，无法收取能量，日志为“数据统计初始化失败”

### ISSUE THREAD

**Issue by AndyJMR** [SuperMonster003/Ant-Forest#420]
**问题描述**
已按前面方法修改了代码，又出现无法收取能量，日志为“数据统计初始化失败”。
手动“点击展开好友动态”可收取

**日志截图**
![image](https://user-images.githubusercontent.com/10118161/106406052-0d2cf980-6473-11eb-941f-771bc3e7a62d.png)

**软件硬件信息**
操作系统: MIUI 12.0.1
设备型号: 小米8
Auto.js版本: 4.1.1 Alpha2 
项目版本: v1.9.25

**Comment by xy3217991** [comment]
我的小米10也是这种情况，MIUI 12.2.9

**Comment by wen704** [comment]
有个临时解决方案
![issue:419](https://github.com/SuperMonster003/Ant-Forest/issues/419)

**Comment by AndyJMR** [comment]
> 有个临时解决方案
> ![issue:419](https://github.com/SuperMonster003/Ant-Forest/issues/419)

亲测有效，多谢！

**Comment by SuperMonster003** [comment]
#419
