### ISSUE TITLE
Bug反馈: [ 有能量但无法自动收取，无报错，日志：无能量球可操作 ]

### ISSUE THREAD

**Issue by ygYang** [SuperMonster003/Ant-Forest#423]
**问题描述**
自己和好友有可收取能量，可从列表进入到好友森林，但无法自动收取，2秒后返回到列表。
（偶尔会收一个，但同一个人的其他能量未收取）
1306行 和 5483行 已经按其他Issue改过。

**日志截图**
![2](https://user-images.githubusercontent.com/26159532/106727767-c2fc7180-6646-11eb-85b2-15d8058b0979.png)

**软件硬件信息**
操作系统: [ Flyme 8.1.5.0A  Android8.1.0]
设备型号: [ 魅族 16th ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.25 ]
支付宝版本: [ 10.2.13 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by keniji** [comment]
我也是有这报错，然后晚上是可以收的，所以我怀疑是支付宝改版后，背景颜色改变导致的(晚上森林颜色和白天是不一样的)。但是其他几个issue里他们都说改完就好，搞得我都怀疑人生了…

**Comment by ygYang** [comment]
> 我也是有这报错，然后晚上是可以收的，所以我怀疑是支付宝改版后，背景颜色改变导致的(晚上森林颜色和白天是不一样的)。[问题]，，...

刚试了下，晚上可以，有可能就是背景问题

**Comment by dotama** [comment]
1308行 in_page_rex_spe: /点击展开好友动态|今天|昨天|\d{2}-\d{2}/, // > cY(0.85)

**Comment by ygYang** [comment]
> 1308行 in_page_rex_spe: /点击展开好友动态|今天|昨天|\d{2}-\d{2}/, // > cY(0.85)

还是不行

**Comment by meetinnet** [comment]
都在自己研究啊。。哎，我也改了1306行 和 5483行 ，不管用呀。

**Comment by zongzhec** [comment]
同反馈此问题

**Comment by ygYang** [comment]
执行 Ant_Forest_Settings，
收取功能 -> 能量球样本采集 -> 颜色与阈值，
帮收（橙色）能量球下面的识别阈值 91 改成 23

**Comment by SuperMonster003** [comment]
v2.0.1 已尝试解决上述问题
如果问题复现 可重新反馈
此 issue 暂时关闭
