### ISSUE TITLE
Bug反馈: [ 黑鲨1无法上划解锁 ]

### ISSUE THREAD

**Issue by dotama** [SuperMonster003/Ant-Forest#424]
**问题描述**
无法上划, 但是上划了能自动的PIN解锁

**日志截图**
![微信图片_20210204024859](https://user-images.githubusercontent.com/25058407/106794545-f6192200-6693-11eb-8e16-d19fd9080dbe.png)

**软件硬件信息**
操作系统: [ 安卓10]
设备型号: [ blackshark SKR-A0 ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.25 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Ant-Forest/issues/105#issuecomment-536177953
提供解锁布局信息

**Comment by dotama** [comment]
> 参阅 [#105 (comment)](https://github.com/SuperMonster003/Ant-Forest/issues/105#issuecomment-536177953)
> 提供解锁布局信息
[!Debug_Info.zip](https://github.com/SuperMonster003/Ant-Forest/files/5994108/Debug_Info.zip)
感谢大神百忙之中查阅!

**Comment by SuperMonster003** [comment]
仔细看了下 应该不是没有识别到布局
是上滑时的时常或距离参数不合适导致上滑不完全
可尝试在配置工具中恢复解锁功能的全部参数为默认值
然后在解锁时不要干预脚本的上滑过程
在上滑过程中 脚本会自动尝试不同的参数 而且应该能看到每次上滑的动作
如果脚本尝试几分钟后依然没有成功 且已经停止了上滑动作 说明自动尝试失败
