### ISSUE TITLE
Bug反馈: 无法收取能量，无法识别防护罩

### ISSUE THREAD

**Issue by LeonWLeon** [SuperMonster003/Ant-Forest#425]
**问题描述**
进入好友森林以后无法收取可收取的能量球，对于有防护罩的也无法识别

**日志截图**

![微信图片_20210205123449](https://user-images.githubusercontent.com/59272725/106990105-93687900-67ae-11eb-8eba-5da183cdf025.jpg)

**软件硬件信息**
操作系统: [ 如: EMUI 10.0.0 ]
设备型号: [ 如:华为MATE10 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.25 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by keniji** [comment]
见issue #423 吧, 应该是同一个问题.

**Comment by SuperMonster003** [comment]
v2.0.1 已尝试解决上述问题
如果问题复现 可重新反馈
此 issue 暂时关闭
