### ISSUE TITLE
Bug反馈: 进去蚂蚁森林好友列表滑动的时候报错

### ISSUE THREAD

**Issue by huanglihang888** [SuperMonster003/Ant-Forest#426]
![Screenshot_20210206_084943](https://user-images.githubusercontent.com/78626952/107103400-79837080-6858-11eb-85c8-560c84d9f38e.jpg)
![Screenshot_20210206_084915_org autojs autojspro](https://user-images.githubusercontent.com/78626952/107103403-7b4d3400-6858-11eb-8144-951a01b26b96.jpg)

**问题描述**
清晰且简明地描述此问题

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [  安卓10.0 ]
设备型号: [ 华为mate30Pro ]
Auto.js版本: [ 8.0.0-5 ]
项目版本: [  v1.9.25]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
v2.0.1 默认修改了排行榜滑动策略
如果使用控件滚动策略或修改为模拟滑动策略后
上述问题复现 可继续反馈
此 issue 保留 28 天
