### ISSUE TITLE
Bug反馈:_reentry is not defined.

### ISSUE THREAD

**Issue by meetinnet** [SuperMonster003/Ant-Forest#427]
最近因为不能收能量，照着各个issue改的有点乱，也不知道是改错了哪里，现在就报这个错误。
重新下载了覆盖安装，也是报这个错，搞不清了。

ReferenceError：“_renntry” is not defined.(Ant_Forest_Launcher.js#5061)

我搜了一下js里面，这个renntry函数是有定义过的。。再深入就不懂了。

反正这几个礼拜就没自动收取成功过。

**Comment by SuperMonster003** [comment]
可使用项目部署工具重新部署项目
或下载项目数据包后手动更新项目
如上述问题复现 可继续反馈
此 issue 保留 4 天

**Comment by meetinnet** [comment]
2.0.1 正常运行了。谢谢。
