### ISSUE TITLE
Auto.js:错误:Error: out of region

### ISSUE THREAD

**Issue by YYYANg2** [SuperMonster003/Ant-Forest#429]
排行榜都进不去，卡在自己页面。
Auto.js:错误:Error: out of region:
    region = [144, 384,1152,768],
image.size = [1080,2400](file://android _asset/modules/__images__.js#523)

**软件硬件信息**
操作系统: [安卓11 ]
设备型号: [小米11]
Auto.js版本: [4.1.1 Alpha2 ]
项目版本: [v2.0.1 ]

**Comment by SuperMonster003** [comment]
请提供包含上述报错的日志截图
以方便定位并排查问题

**Comment by YYYANg2** [comment]
> 请提供包含上述报错的日志截图
> 以方便定位并排查问题

![Screenshot_2021-02-09-16-50-32-420_org autojs aut](https://user-images.githubusercontent.com/78776953/107339384-8bf9e600-6ab4-11eb-95b5-dbe8e01cecb5.jpg)

**Comment by YYYANg2** [comment]
> 请提供包含上述报错的日志截图
> 以方便定位并排查问题

![Screenshot_2021-02-09-16-50-32-420_org autojs aut](https://user-images.githubusercontent.com/78776953/107339530-af249580-6ab4-11eb-9cd1-b13946351a38.jpg)

**Comment by SuperMonster003** [comment]
1. 是否修改过以下配置参数
配置工具 -> 收取功能 -> 能量球样本采集 -> 能量球识别区域
如未修改过 请提供一下参数截图
如已修改 请尝试恢复默认值后再运行项目
2. 设备是否具备两种 (或以上) 的分辨率
如具备 请尝试调整至其他分辨率后再运行项目

3. 另外提供一下以下测试代码的运行结果
通常 测试代码的运行结果是内容相同的两行
```js
images.requestScreenCapture();
let capt = images.captureScreen();
console.log(capt.getWidth() + '×' + capt.getHeight()); // eg: 1080×2400
console.log(device.width + '×' + device.height); // eg: 1440×3200
```

**Comment by YYYANg2** [comment]
@SuperMonster003 

![1612865437940](https://user-images.githubusercontent.com/78776953/107348808-68886880-6abf-11eb-8fad-493b0d166fbc.jpg)
2.换了分辨率还是不行。
第三点不会搞，本人小白。。。

**Comment by SuperMonster003** [comment]
设备宽高与截图尺寸不同 需要做特殊适配 而且需要做大量的代码重构
上述现象目前是首次出现 鉴于工作量及问题出现概率 将不考虑做特殊适配
此 isuue 将标记为无法完成

**Comment by Sq-List** [comment]
出现同样问题。
机型: 小米11![Screenshot_2021-02-22-00-07-42-391_org.autojs.autojs.jpg](https://user-images.githubusercontent.com/25433052/108630858-fdb53500-74a1-11eb-919b-1e239c9f7e55.jpg)

**Comment by SuperMonster003** [comment]
v2.0.3 已尝试修复上述问题
如仍有异常 可继续反馈

**Comment by zyjStart** [comment]
我这也出现了这种问题，但是只有打包之后才会出现这种问题，没打包可以正常跑
