### ISSUE TITLE
Bug反馈: MIUI 12.5自动解锁无法点亮屏幕

### ISSUE THREAD

**Issue by liujiayi771** [SuperMonster003/Ant-Forest#431]
**问题描述**
升级MIUI 12.5开发版之后，定时任务不能自动点亮屏幕，手动点亮屏幕之后能继续自动上滑输入密码解锁自动完成任务。日志里没有看到有报错。

**软件硬件信息**
操作系统: [ 如: 安卓11 ]
设备型号: [ 如: 小米 10 pro ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.0.2 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by liujiayi771** [comment]
![Screenshot_2021-02-12-17-31-42-375_org autojs autojs](https://user-images.githubusercontent.com/13622031/107751378-f3957880-6ce2-11eb-9ac6-45e1956053f5.jpg)
这里我设置了一个17.27的定时任务，到17.28我手动点亮屏幕后能正常解锁，我不打开屏幕就会一直黑屏，不能自动亮屏。

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Ant-Forest/issues/134

**Comment by liujiayi771** [comment]
给了所有权限还是不行。但是我发现他一般会比我设置的时间晚五分钟左右能点亮屏幕自动开始运行。

**Comment by liujiayi771** [comment]
![Screenshot_2021-02-13-07-40-40-107_org autojs autojs](https://user-images.githubusercontent.com/13622031/107836509-0354a180-6d63-11eb-8058-7adfce470b1e.jpg)
![Screenshot_2021-02-13-08-47-14-252_org autojs autojs](https://user-images.githubusercontent.com/13622031/107836516-08b1ec00-6d63-11eb-8db1-09b0c827e098.jpg)
比如这里7.42的任务到7.45才开始，延迟接力的任务倒是差不多时间开始的

**Comment by SuperMonster003** [comment]
受设备系统的节电设置等限制
Auto.js 可能无法在后台实现及时唤醒
暂无法通过代码接触上述限制

**Comment by liujiayi771** [comment]
> 受设备系统的节电设置等限制
> Auto.js 可能无法在后台实现及时唤醒
> 暂无法通过代码解除上述限制

我之前测试的时候用的都是一次性任务，现在每天早上他也能自己唤醒，晚几分钟也不影响什么，现在每天都正常在收能量的

**Comment by SuperMonster003** [comment]
如上述问题复现 或出现其他项目问题
可发起新的 issue 反馈
此 issue 暂时关闭
