### ISSUE TITLE
能够进入农场，打开第一个好友农场时会报错

### ISSUE THREAD

**Issue by xy3217991** [SuperMonster003/Ant-Forest#432]
小米10，MIUI12.2.9  Auto.js4.1.1
错误日志：

07:14:23.199/E: Error: out of region: region = [767,1451,302,866], image.size = [2340,1080] (file:///android_asset/modules/__images__.js#523)
Error: out of region: region = [767,1451,302,866], image.size = [2340,1080]
    at buildRegion (file:///android_asset/modules/__images__.js:523:0)
    at file:///android_asset/modules/__images__.js:395:0
    at _chkInvtBtn (/storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:6191:0)
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-global.js:207:0
    at _swipe (/storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:6022:0)
    at /storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:5327:0
    at /storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:6995:0
    at /storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:7023:0

**Comment by SuperMonster003** [comment]
尝试打开设备的屏幕旋转开关
打开 Auto.js 后将设备横屏放置
等 Auto.js 软件横向显示后再竖直方向放置设备
等待 Auto.js 恢复竖直显示后再尝试运行项目
如问题依然出现 可再次反馈

**Comment by xy3217991** [comment]
可以的，已解决，谢谢
