### ISSUE TITLE
功能建议: [ 定时启动时能检测ant-forest-launcher是否运行中 ]

### ISSUE THREAD

**Issue by yzliufujin** [SuperMonster003/Ant-Forest#433]
[ 包括但不限于 项目功能改进/功能添加/代码优化/执行逻辑优化... ]
建议增加检测功能：在设置的定时启动ant-forest-launcher时，能检测该脚本是否已处于运行中，如该脚本正在运行中，则此定时任务自动作废，避免出现ant-forest-launcher脚本同时运行好几个的问题。

**Comment by SuperMonster003** [comment]
预期情况应该是新的任务 (包括自动定时任务和手动运行的任务) 自动排队
在前面的任务运行完毕 (或因超时等原因退出) 后再自动运行

如果脚本出现非预期情况
请按照如下模板进行反馈

情景复现: 
(如  当前正在运行项目  任务列表中有一个 1 分钟后运行的定时任务)
预期情况:
(如  当前任务运行了 3 分钟  运行期间  定时任务排队并在当前任务结束后自动运行)
实际情况:
(如  当前任务尚未结束 定时排队的任务就自动运行了)
相关材料:
(屏幕截图 日志截图 等)
