### ISSUE TITLE
排行榜未复查

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#435]
**问题描述**
我在排行榜样本复查中，关闭了列表状态差异，打开样本点击记录和最小倒计时阈值（1min）。
然后排行榜在第一次检查过程中，列表中有某个好友显示1min后成熟，但是这次检查结束后，未开始复查。
有某个好友的倒计时为1min，应该已达到了阈值，不知为何没复查

**日志截图**
![18cfb5cf7a957841959173622b184d7](https://user-images.githubusercontent.com/9878167/108932880-0ca80d00-7685-11eb-8c02-907f65ae78aa.jpg)

**软件硬件信息**
操作系统: 安卓10.0
设备型号: iQOO5
Auto.js版本: 4.1.1 Alpha2

**其他**
无

**Comment by SuperMonster003** [comment]
感谢反馈
如经场景复原后问题确实如上所述 将于下一版本尝试修复

**Comment by linfeizheng** [comment]
请问您是否会在修复后关闭此issue
如果会我可以在issue被关闭后更新代码，否则我不知如何知晓后续进展

**Comment by SuperMonster003** [comment]
上述问题会在新版本修复

新版本发布后
若使用的项目是 v2.x 版本 且没有关闭 "自动检查更新" 功能
则项目会自动提示版本更新
根据提示更新项目即可

当前 issue 会在你提交新版项目的使用反馈后
根据反馈情况决定是否关闭
若 1 个月内没有反馈
issue 将会被开发者手动关闭

**Comment by SuperMonster003** [comment]
v2.0.3 已尝试修复上述问题
如使用新版本后问题复现 可继续反馈

**Comment by linfeizheng** [comment]
可以了
