### ISSUE TITLE
偶尔进入某个好友的主页后会停留比较久

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#436]
**问题描述**
排行榜中有几个好友都开启了能量罩并且都有未收能量，会有某个好友A，程序在进入A主页时会停留大约十几二十秒再返回列表，而其他几个好友，进入主页后发现有能量罩就马上返回列表了

**日志截图**
时长比较久不好录视频，见谅

**软件硬件信息**
操作系统: 安卓10.0
设备型号: iQOO5
Auto.js版本: 4.1.1 Alpha2

**其他**
无

**Comment by SuperMonster003** [comment]
可以使用配置工具
在消息提示功能下勾选 "开发者测试模式"
然后在下次出现问题时提供上述 "好友 A" 相关的日志截图
有些问题通过日志也可定位排查

**Comment by linfeizheng** [comment]
文件中搜索 2021-02-28/07:30:19.576
应该是能量罩时间采集失败

[1auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6059087/1auto.js-log.log)

**Comment by SuperMonster003** [comment]
原因应该是脚本点击展开更多动态按钮没成功
能量罩信息采集目前依赖动态列表
下一版将尝试修复此问题

**Comment by linfeizheng** [comment]
可能不是这个原因，我看到更多按钮被点击了
按你的想法修复后，下个版本我再看看
谢谢

**Comment by linfeizheng** [comment]
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6128240/auto.js-log.log)

时间：2021-03-12/14:35:25.480 

“点击加载更多”按钮进去就已被点击，不知为何程序还说定位超时

不过停留时间比2.0.2短很多了，实在不好修复也不影响大局了(^_^)

**Comment by SuperMonster003** [comment]
首次进入好友森林  需点击 "点击展开好友动态" 出现动态列表

动态列表出现后  需点击 "点击加载更多" 以扩展列表  (因为能量罩信息采集是基于列表信息的)

由于 "点击加载更多" 现已变更为 "加载更多"  导致脚本无法自动扩展列表

v2.0.4 已尝试解决上述问题
如问题依然存在  可继续反馈

**Comment by linfeizheng** [comment]
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6182104/auto.js-log.log)

时间 2021-03-20/23:21:21.438

还是有这种情况

**Comment by waitingwx** [comment]
一样的情况，今天下载的最新版本，已经可以了，手机型号1+7pro Android10

**Comment by linfeizheng** [comment]
这几天没有遇到了
