### ISSUE TITLE
Bug反馈: [ 解锁上滑失败 ]

### ISSUE THREAD

**Issue by lebron77** [SuperMonster003/Ant-Forest#437]
**问题描述**
如果开了屏上指纹就没办法上滑到密码解锁 关闭屏上指纹则可以正常解锁

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [  安卓11.0 ]
设备型号: [ 小米10]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 2月11版本 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Ant-Forest/issues/105#issuecomment-536177953
提供解锁布局信息

**Comment by lebron77** [comment]
![Uploading container-page.png…]()
![unlock-bounds](https://user-images.githubusercontent.com/79761042/109465174-bed73e80-7aa2-11eb-920a-b0d71aa8e898.png)
![unlock-page](https://user-images.githubusercontent.com/79761042/109465190-c39bf280-7aa2-11eb-9832-1ae3fe8865bc.png)
[Uploading device-info.txt…]()

**Comment by lebron77** [comment]
不好意思 回复晚了

**Comment by SuperMonster003** [comment]
device-info.txt
上述文件未上传成功

**Comment by lebron77** [comment]
[Uploading device-info.txt…]()

**Comment by lebron77** [comment]
不会上传文件…

**Comment by lebron77** [comment]
具体就是我图上这个指纹解锁 开着就没办法上滑到解锁页面 关了就可以正常运行

**Comment by lebron77** [comment]
现在发现第一次上滑到解锁页面失败后 5分钟后第二次能够成功解锁

**Comment by lebron77** [comment]
![Uploading Screenshot_2021-03-02-08-10-43-351_org.autojs.autojs.jpg…]()

**Comment by lebron77** [comment]
![Uploading Screenshot_2021-03-02-08-10-43-351_org.autojs.autojs.jpg…]()

**Comment by SuperMonster003** [comment]
建议将所有文件打包为 zip 格式再上传
具体上传方法参阅 https://github.com/SuperMonster003/Ant-Forest/issues/415#issuecomment-775757968

**Comment by lebron77** [comment]
[解锁.zip](https://github.com/SuperMonster003/Ant-Forest/files/6074668/default.zip)

**Comment by lebron77** [comment]
已上传

**Comment by Liujiansongsongsong** [comment]
小米11同上

**Comment by SuperMonster003** [comment]
原因应该是滑动起点位置落在了指纹识别区域之内
尝试运行配置工具 -> 自动解锁 -> 起点位置
修改为 0.7 或更小的值

**Comment by Liujiansongsongsong** [comment]
> 小米11同上

滑动策略，连续路径，起点0.6；解决问题

**Comment by lebron77** [comment]
可以 已经解决 谢谢大佬
