### ISSUE TITLE
手机摄像头被遮挡时无法启动脚本

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#438]
**问题描述**
我下班骑车前会将手机放在口袋（行驶过程中会到达下一次执行之间），当我停下后掏出手机，会发现在应当启动脚本的时间没有启动脚本（解锁后看见autojs的立即开始or取消弹窗，下次执行时间可能为无也可能为设置的保险间隔时间）
感觉是手机摄像头被挡住的原因，
请问这是手机自身的问题，还是脚本可以优化

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ 如: android10.0 ]
设备型号: [ 如: iQOO5 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]

**Comment by SuperMonster003** [comment]
1. 检查手机是否开启了类似 "屏幕关闭时防止意外操作" (Prevent accidental operations with screen off) 的设置
2. 查看日志  关注在应该启动项目的时刻是否有 Auto.js 运行记录  若有记录  说明 Auto.js 完成了定时启动  否则检查设备是否限制了 Auto.js 的后台唤醒
