### ISSUE TITLE
启动了当前时间之前的任务

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#439]
**问题描述**
在下面的log文件中搜索这样一句话   2021-03-02/07:31:11.422/D: -> 下次运行: 2021/03/02 07:29:38
在7:31启动了7:29的任务

**日志截图**
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6067465/auto.js-log.log)

**软件硬件信息**
操作系统: 安卓10.0
设备型号: iQOO5
Auto.js版本: 4.1.1 Alpha2

**其他**
提一下，其实不影响正常使用

**Comment by SuperMonster003** [comment]
感谢反馈
将于下一版修复上述问题
