### ISSUE TITLE
任务莫名终止

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#440]
问题描述
7点13之后任务不知道为啥终止了，7点26我醒来一看，手动启动了任务
请问终止的原因是啥

日志截图
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6067709/auto.js-log.log)

软件硬件信息
操作系统: 安卓10.0
设备型号: iQOO5
Auto.js版本: 4.1.1 Alpha2

**Comment by linfeizheng** [comment]
我是设置的每日7点启动任务
执行是执行了，就是执行到7点13就没再进行下去了

**Comment by SuperMonster003** [comment]
1. 同时运行不同的项目
2. 在短时间同时运行大量脚本

Auto.js 执行多个脚本是并发执行的
除非在代码中检测引擎队列实现排队
同时运行不同的项目
将导致项目执行逻辑超出预期
短时间内执行大量脚本
如果不在代码中做特别处理
将导致 Auto.js 消耗大量资源甚至崩溃
