### ISSUE TITLE
Bug反馈:一加手机系统双开支付宝 脚本暂停

### ISSUE THREAD

**Issue by github-sxw** [SuperMonster003/Ant-Forest#441]
**问题描述**
一加手机双开支付宝，打开支付宝时，脚本暂停，不能自动选择支付宝1，需要手动选择。

**日志截图**

![7f843503aefc66d6398928c382fe379](https://user-images.githubusercontent.com/44339299/110724722-4ebe7a80-8251-11eb-89a1-f2f3f3ae418a.jpg)

**软件硬件信息**
操作系统: [ 如: 安卓10 ]
设备型号: [ 如: 一加5T ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.0.3 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
这个问题之前有人提到过
已经做了尽最大努力的兼容处理
此项目将不再继续为当前问题做进一步兼容
