### ISSUE TITLE
Bug反馈: 不能消除提示层进入解锁页面

### ISSUE THREAD

**Issue by lixifei12138** [SuperMonster003/Ant-Forest#442]
今天突然不能提示层进入解锁界面，需要手动上滑，然后可以自动解锁并继续进行。修改上滑时长和起点终点没有作用
![Screenshot_2021-03-12-11-23-35-592_org autojs autojs](https://user-images.githubusercontent.com/77929669/110887691-5bbe8680-82b0-11eb-82fb-1a022a9b0a56.jpg)

权限已给，依旧没有作用
**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ 如: 安卓11.0 ]
设备型号: [ 如: 小米10u ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.0.3 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by lixifei12138** [comment]
我发现了   在锁屏有通知的时候不能识别提示层
当锁屏没有通知时可以正常解锁

**Comment by SuperMonster003** [comment]
在有通知时 脚本在提示层页面是否有上滑动作

**Comment by lixifei12138** [comment]
> 在有通知时 脚本在提示层页面是否有上滑动作

经过这几天测试，摸不清了具体情况了。有时候有通知也可以解锁，有时候解锁不了。重新安装了auto.js和脚本之后现在提示层也进不去了。自动解锁完全失效了。

**Comment by lixifei12138** [comment]
> 在有通知时 脚本在提示层页面是否有上滑动作

现在息屏界面跳不过  提示层跳不过   手动帮忙跳过可以自动输入密码解锁

**Comment by lixifei12138** [comment]
![Uploading Screenshot_2021-03-17-19-51-58-987_org.autojs.autojs.jpg…]()
还是这个问题
可是权限已经给了

**Comment by lixifei12138** [comment]
> 在有通知时 脚本在提示层页面是否有上滑动作

还需要什么反馈嘛  😥这个情况好久了

**Comment by lixifei12138** [comment]
昨天半夜用了一次，竟然可以自己解锁了。原封不动到早上就又不行了。。。

**Comment by China-Uncle** [comment]
设置滑动范围 0.9-0.2,时间 800MS 试试.

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Ant-Forest/issues/437#issuecomment-789718778 设置滑动起始点参数
