### ISSUE TITLE
黑名单功能无法刷新好友列表

### ISSUE THREAD

**Issue by NonoKing** [SuperMonster003/Ant-Forest#443]
### **问题描述**
想要不偷指定好友的能量，就尝试了一下自定义黑名单的功能。
发现在扫描好友列表时，到列表底部之后，就停在那里了，触屏操作也不太好使，只能按音量键停止。
停止之后，好友列表信息也没有保存到项目中。

### **日志截图**
![微信图片_20210315161210](https://user-images.githubusercontent.com/33653932/111122634-40ea5b80-85a9-11eb-80e3-b0e59071d9e0.jpg)
![微信图片_20210315161222](https://user-images.githubusercontent.com/33653932/111122644-45167900-85a9-11eb-9466-9df57ce6dcb3.jpg)

### **软件硬件信息**
操作系统: [ MIUI12.0.3]
设备型号: [ Redmi Note7 ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v2.0.3 ]

### **其他**
**小bug1：**
在偷能量扫描好友列表的时候，有时候，由于可偷取的能量在最底部（没有显示完全的那种），会进入到显示完全的最后一个好友主页（但是这个好友并没有可偷取的），这其实没什么大碍，过一会儿就返回接着往下扫了。但是**问题**就出在，这个误入的好友，如果正好又是个“该好友已归隐山林”的好友，就会导致返回不了，无法接着进行下去了。

**小建议1：**
每次定时任务都会先在自己主页收取，然后去扫描排行榜，根据最短的倒计时设置定时任务。但是如果自己有个能量球时间比排行榜的短，会存在自己能量会被偷的情况233333。所以我在想，能不能每次扫描完排行榜之后，再回到自己主页，跟自己的能量球做个时间长短对比嘞？

**Comment by NonoKing** [comment]
真快 刚提没多久 大佬就修复了哈哈哈哈

**Comment by SuperMonster003** [comment]
`小bug1` 将于下一版尝试修复
`小建议1` 参阅 `配置工具 -> 自收功能 -> 返检监控 -> 返检阈值` 的参数配置提示

**Comment by NonoKing** [comment]
> `小bug1` 将于下一版尝试修复
> `小建议1` 参阅 `配置工具 -> 自收功能 -> 返检监控 -> 返检阈值` 的参数配置提示

谢谢大佬！大佬真强！！
