### ISSUE TITLE
Bug反馈: [ 定时任务启动时，唤醒屏幕无法解锁 ]

### ISSUE THREAD

**Issue by JasonLeeTing** [SuperMonster003/Ant-Forest#447]
**问题描述**
定时任务唤醒屏幕，屏幕常亮，一直无法进入图形解锁界面
若手动指纹解锁，会自动触发任务

**日志截图**
![1615908605770](https://user-images.githubusercontent.com/80761609/111492907-0e428d80-8778-11eb-826d-476cd1797c37.jpg)

**软件硬件信息**
操作系统: [ 安卓11 ]
设备型号: [ 小米10 Ultra ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v2.0.5 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by lixifei12138** [comment]
情况好像差不多，有人说换个主题。。。

**Comment by JasonLeeTing** [comment]
> 情况好像差不多，有人说换个主题。。。

换过主题，使用系统自带主题也是有类似的问题，有的时候都不唤醒屏幕

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Ant-Forest/issues/437#issuecomment-789718778 设置滑动起始点参数
