### ISSUE TITLE
Bug反馈: 小米11不能自动解锁

### ISSUE THREAD

**Issue by OCDcreator** [SuperMonster003/Ant-Forest#448]
**问题描述**
自动解锁亮屏后不能上划进入输入密码的界面，需要手动帮助上划。

**日志截图**
![697C3DE4-6F22-4735-9D58-94D024B2A7D6](https://user-images.githubusercontent.com/62931432/111502799-266ada80-8781-11eb-8768-b8e69a62fd88.jpeg)

**软件硬件信息**
操作系统: [ 如: miui12]
设备型号: [ 如: xiaomi 11 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.0.5]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by OCDcreator** [comment]
所有权限都给了

**Comment by perhaps007** [comment]
换个主题就好了，目前使用MIX主题，亲测可以解锁

**Comment by lixifei12138** [comment]
跟我情况一样

**Comment by lixifei12138** [comment]
> 换个主题就好了，目前使用MIX3主题，亲测可以解锁

我换了主题也是没用   感觉就像是没有上滑动作   有没有啥主题下滑解锁的。。。

**Comment by mhhbb** [comment]
我是所有权限给了，手机定时到了后只要息屏状态下就无法解锁（小米10）

**Comment by lixifei12138** [comment]
> 我是所有权限给了，手机定时到了后只要息屏状态下就无法解锁（小米10）

我是时好时坏的现在   摸不清脉搏看他心情

**Comment by China-Uncle** [comment]
> 换个主题就好了，目前使用MIX3主题，亲测可以解锁

小米10 用了 mix3 主题.也不行哎.

**Comment by China-Uncle** [comment]
可以尝试 起始范围 0.9-0.2,时间 800MS ,小米10 经典主题可以使用.

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Ant-Forest/issues/105#issuecomment-536177953 提供解锁布局信息
参阅 https://github.com/SuperMonster003/Ant-Forest/issues/437#issuecomment-789718778 设置滑动起始点参数
