### ISSUE TITLE
Bug反馈: 进入好友列表后异常报错停止

### ISSUE THREAD

**Issue by Z-L-X** [SuperMonster003/Ant-Forest#451]
手机：小米8
auto.js：4.1.1 A2
日志：
22:16:24.077/E: Error: out of region: region = [767,1394,302,832], image.size = [2248,1080] (file:///android_asset/modules/__images__.js#523)
Error: out of region: region = [767,1394,302,832], image.size = [2248,1080]
    at buildRegion (file:///android_asset/modules/__images__.js:523:0)
    at file:///android_asset/modules/__images__.js:395:0
    at _chkInvtBtn (/storage/emulated/0/脚本/2.5/Ant-Forest-master/ant-forest-launcher.js:5952:0)
    at file:/storage/emulated/0/脚本/2.5/Ant-Forest-master/modules/ext-global.js:207:0
    at _swipe (/storage/emulated/0/脚本/2.5/Ant-Forest-master/ant-forest-launcher.js:5783:0)
    at /storage/emulated/0/脚本/2.5/Ant-Forest-master/ant-forest-launcher.js:5088:0
    at /storage/emulated/0/脚本/2.5/Ant-Forest-master/ant-forest-launcher.js:6754:0
    at /storage/emulated/0/脚本/2.5/Ant-Forest-master/ant-forest-launcher.js:6782:0

**Comment by Z-L-X** [comment]
重启手机后异常消失

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Ant-Forest/issues/432#issuecomment-781895943
