### ISSUE TITLE
交流研讨: [ 支付宝解锁 ]

### ISSUE THREAD

**Issue by kanxianbei** [SuperMonster003/Ant-Forest#452]
这个是不是要把支付宝的密码保护关掉啊，我运行的时候一直卡在支付宝解锁界面进不去，只能人工自己解锁才能进入

**Comment by SuperMonster003** [comment]
项目不支持对支付宝手势锁的自动解锁

v2.1.0 加入对手势锁的检测
如检测到 则停止脚本运行
需要移除手势锁才能使用此项目
