### ISSUE TITLE
保护罩点击记录和列表底部判断问题

### ISSUE THREAD

**Issue by ljaist** [SuperMonster003/Ant-Forest#453]
2.0.5版本。之前的几个版本也有类似问题。
1.部分好友保护罩会点击，在好友森林里留下点击记录。部分有点击但没有留下记录，部分能判断成功，不点击也没留下记录。然后能量罩黑名单就只生成部分好友，有的好友会每次运行都点击。
2.我的好友列表底部会有几个未开通森林的人，在其名字右侧是绿色的“邀请”左侧没有序号，滑动到此时常常就不动了滑不到“没有更多了”几个字，导致无限循环运行

**Comment by SuperMonster003** [comment]
请提供项目运行日志

运行配置工具 (ant-forest-settings.js)
1. 消息提示 -> 勾选 "开发者测试模式"
2. 本地日志 -> 打开 "总开关"

自此运行项目后
日志将保留在项目的 log 文件夹下
如 auto.js-log.log


另外脚本在检测到邀请按钮后就认为到达了底部
不再继续往下滑动
这是为了节省目标采集时间
因为在邀请按钮之后不再有可采集的目标
脚本每次循环都会有触发条件
日志中可以体现具体的触发条件

上述第一个问题我没看明白
希望做进一步阐述

**Comment by ljaist** [comment]
更新了2.1.0版本，修改了循环条件，这两个问题解决了。
没用工具时，有保护罩的，点击会提示“他被保护罩保护”并好友动态里会显示我的点击动态“xxx来偷能量但被保护罩阻挡”。如果非共同好友点击过，动态里会记录“TA的好友来偷能量但被保护罩阻挡”。
在早期的版本中，遇到有保护罩的好友，不会在动态里留下我的点击记录，且会生成保护罩黑名单。2.1.0之前的好几个版本都存在 或者没有生成黑名单、黑名单生成不全、多次运行会反复在好友动态里留下被保护罩阻挡记录的问题。2.1.0版本使用，虽然仍然没有生成保护罩黑名单（有开保护罩的好友，但运行正常结束后该列表仍为空），但是多次运行时，只会留下一次被保护罩阻挡的记录，算是解决了反复点击的问题吧。
无限循环问题，修改了排行榜样本复查设置，把列表状态差异条件取消了就不会单次运行无限循环了，可能是好友太多的问题。

**Comment by SuperMonster003** [comment]
提供详细的运行日志以方便定位排查问题
