### ISSUE TITLE
Bug反馈: [ 内存溢出，导致运行中止 ]

### ISSUE THREAD

**Issue by PenghuiCai** [SuperMonster003/Ant-Forest#457]
**问题描述**
我的好友有200多个，自动定时任务触发运行，正在运行中突然停止运行，看日志是内存溢出，查看内存使用情况占了1.3G的内存

**日志截图**
java.lang.OutOfMemoryError:

**软件硬件信息**
操作系统: [ 如: 安卓11 ]
设备型号: [ 如: 小米 11 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.1.0 ]

**其他**
[ 建议每次定时任务运行结束时触发内存回收 ]

**Comment by SuperMonster003** [comment]
内存溢出的情况基本上是不可避免的
因为免费版的最终版已经很久不维护且不会再维护了
想在aj上使用js代码实现底层的内存回收是不可能的
即使使用了java.lang.System.gc()也没有作用
目前已知的方案也只能是重启aj
另外可以通过代码尽量降低oom发生频率

**Comment by PenghuiCai** [comment]
感谢回复！
请问升级8.0是否能解决内存溢出的情况？

**Comment by SuperMonster003** [comment]
将会有所改善.
但不保证不会出现 oom .
我只是在 8.0.x 版本的时候做过几天的试运行比较.
后面就没再用 8.x 版本.
除非用户反馈 8.x 的兼容问题.

另外 8.x 版本从 8.3.16 (不含) 后不在支持支付宝应用的控件抓取. (9.x也不支持)
因此项目最高只能运行在 8.3.16 版本.
