### ISSUE TITLE
Bug反馈: 一加9的coloros不能解锁亮屏

### ISSUE THREAD

**Issue by tagaga** [SuperMonster003/Ant-Forest#458]
**问题描述**
一加9 ，coloros，无法激活手机亮屏，只能手动电源键亮屏后脚本才能运行，因为无法激活手机，脚本完全不能自动定时运行。密码解锁的功能还是有效的，能够通过设定密码解锁并运行脚本，关键是卡在不能激活手机屏幕亮屏。

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: Coloros android11
设备型号: 一加9
Auto.js版本: 4.1.1 Alpha2
项目版本: 2.1.0

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Ant-Forest/issues/407#issuecomment-722933168
https://github.com/SuperMonster003/Ant-Forest/issues/134
