### ISSUE TITLE
Error: A "version" must be defined forappx.getVerHex()

### ISSUE THREAD

**Issue by 18595842373** [SuperMonster003/Ant-Forest#459]
Error: A "version" must be defined forappx.getVerHex()

**Comment by 18595842373** [comment]
Auto.js  4.1.1 Alpha2
项目版本V2.1.0
**日志截图**:
![3b6fcdd77dde92b393cc835196e3ac3](https://user-images.githubusercontent.com/79901116/115977239-b4b85480-a5a8-11eb-920d-2ff2f5686c98.jpg)

示例:

![2e69392b537fbaba3387e782e3e004b](https://user-images.githubusercontent.com/79901116/115977249-c7cb2480-a5a8-11eb-9124-f29c6617199c.jpg)


小米11  安卓版本10
错误触发条件:正常运行

**Comment by SuperMonster003** [comment]
[ant-forest-deployment-tool.min.zip](https://github.com/SuperMonster003/Ant-Forest/files/6371346/ant-forest-deployment-tool.min.zip)
尝试使用压缩包内的部署工具 (单独的 *.js 文件)

PS:
上述问题是由 Ant-Forest-003 文件夹内缺失可用于识别项目版本的相关文件引起
可能的场景之一是用户在 Auto.js 软件中在项目文件夹右侧进行删除操作
导致文件夹内非隐藏文件 (包括上述可用于识别项目版本的相关文件) 全部被删除
但诸如 `.gitignore` 等隐藏文件无法被删除进而导致项目目录残留
最终使部署工具在备份本地项目步骤时出错
