### ISSUE TITLE
BUG反馈：更新新版本下载反馈链接报错

### ISSUE THREAD

**Issue by k53247l2** [SuperMonster003/Ant-Forest#460]
**问题描述**
使用软件自动更新下载新版本的时候报错了，导致下载不成功

**日志截图**
![Screenshot_20210502_094722_org autojs autojs](https://user-images.githubusercontent.com/27880808/116799438-eb9fe480-ab2b-11eb-9bea-7d4c31e545fc.jpg)

**软件硬件信息**
操作系统: Android10
设备型号: 华为荣耀p40 pro
Auto.js版本: 4.1.1 Alpha2 
项目版本: v2.0.1

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
v2.0.1的更新功能有问题 (后续版本已修复)
可尝试使用项目部署工具完成升级
或在配置工具中使用服务器还原功能间接实现升级

**Comment by k53247l2** [comment]
谢谢，我使用软件的“备份与还原”直接从服务器还原了最新版本，谢谢提醒。
