### ISSUE TITLE
Bug反馈: 黑名单功能  在刷新好友列表时提示错误

### ISSUE THREAD

**Issue by lixifei12138** [SuperMonster003/Ant-Forest#462]
**问题描述**
刷新列表时自动跳转到支付宝好友列表   然后提示错误

**日志截图**

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 小米10u ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.1.0
**其他

**Comment by lixifei12138** [comment]
![IMG_20210513_073527](https://user-images.githubusercontent.com/77929669/118057361-731dfc80-b351-11eb-80bc-0717a52df61d.jpg)

**Comment by SuperMonster003** [comment]
`v2.1.1` 已尝试修复上述问题
使用后如果问题复现 可继续反馈
