### ISSUE TITLE
Bug反馈: [ Vivo系统更新后，能点亮屏幕，但无法自动解锁 ] (Edited)

### ISSUE THREAD

**Issue by youngpopp** [SuperMonster003/Ant-Forest#463]
**问题描述**
Vivo系统更新后，能点亮屏幕，但无法自动解锁；已经重新设置过解锁起点0.6、终点，上滑时长也改为500ms，但是依旧无反应

**日志截图**
14:21:59.560/E: Wrapped java.lang.ArrayIndexOutOfBoundsException: length=1; index=-3 (file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-device.js#1854)
Wrapped java.lang.ArrayIndexOutOfBoundsException: length=1; index=-3
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-device.js:1854:0
    at _stg (file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-device.js:1799:0)
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-device.js:2034:0
    at _unlock (file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-device.js:2099:0)
    at /storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:3895:0
    at /storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:7061:0

**软件硬件信息**
操作系统: 安卓11，originos 1.1.1.13
设备型号: vivo X60 pro+
Auto.js版本: 4.1.1 Alpha2
项目版本: 2.1.0

**Comment by SuperMonster003** [comment]
请提供项目运行日志

运行配置工具 (ant-forest-settings.js)
1. 消息提示 -> 勾选 "开发者测试模式"
2. 本地日志 -> 打开 "总开关"

自此运行项目后
日志将保留在项目的 log 文件夹下
如 auto.js-log.log

另外参阅 https://github.com/SuperMonster003/Ant-Forest/issues/105#issuecomment-536177953
提供解锁布局信息

**Comment by youngpopp** [comment]
日志文件及解锁布局在压缩文件中
[布局文件.zip](https://github.com/SuperMonster003/Ant-Forest/files/6513245/Desktop.zip)

**Comment by Dinert** [comment]
自动解锁屏幕时会亮，但一直进不去输入密码那个界面。解锁不了

**Comment by SuperMonster003** [comment]
@youngpopp @Dinert 
尝试最新版 (v2.1.5) 后如果依然有解锁问题  请新开 (或重开此) issue  此 issue 暂时关闭
