### ISSUE TITLE
Bug反馈: [ 操作完成 无法自动息屏 ]

### ISSUE THREAD

**Issue by derryck404** [SuperMonster003/Ant-Forest#465]
**问题描述**
手机在息屏情况下能够自动开屏解锁操作，但是操作完成后无法自动息屏。已授权Auto.js全部权限了😟，检查日志也无法运行相关帮助，如下图。

**日志截图**
![image](https://user-images.githubusercontent.com/53424148/118391768-9eae2900-b668-11eb-9526-f31bdced3984.png)
![image](https://user-images.githubusercontent.com/53424148/118391793-b71e4380-b668-11eb-9722-521fc74f390f.png)

**软件硬件信息**
操作系统: [ 如: 安卓8.0 ]
设备型号: [ 如: 华为 P9 ]
Auto.js版本: [  4.1.1 Alpha2 ]
项目版本: [ v2.1.0 ]

**Comment by SuperMonster003** [comment]
`v2.1.1` 已去除上述工具对扩展模块的依赖
可尝试升级项目至最新版后再次运行上述工具

**Comment by derryck404** [comment]
[如图，问题已解决。感谢大佬😊
![snipaste20210517_132802](https://user-images.githubusercontent.com/53424148/118436752-f48bdb00-b713-11eb-885b-b8a82d383823.jpg)
