### ISSUE TITLE
能量收取时间过长

### ISSUE THREAD

**Issue by nidelinju** [SuperMonster003/Ant-Forest#466]
设备是小米11，识别到收取一个能量需要用时20秒
![Screenshot_2021-05-16-07-07-18-487_org autojs autojs](https://user-images.githubusercontent.com/84276314/118398715-7f3ede00-b61f-11eb-9178-f4d7b39b0388.jpg)

**Comment by SuperMonster003** [comment]
上述现象是偶发的还是高频的

**Comment by nidelinju** [comment]
之前一两次都是正常运行，后面一直如此，卸载软件和脚本重新安装也是这个情况，换过脚本的版本也不行。

**Comment by nidelinju** [comment]
> 上述现象是偶发的还是高频的

之前一两次都是正常运行，后面一直如此，卸载软件和脚本重新安装也是这个情况，换过脚本的版本也不行。

**Comment by SuperMonster003** [comment]
上述问题目前暂时无法解决
此 issue 将标记为 "无法完成"
