### ISSUE TITLE
Bug反馈: [ 新增的能量雨收集模块无法使用，报申请截图权限失败 ]

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Ant-Forest#467]
**问题描述**
新增的能量雨收集模块无法使用，报”截图权限申请失败“，但是主程序运行时无此报错

**日志截图**
![image](https://user-images.githubusercontent.com/50188136/118442443-29e8f680-b71d-11eb-879f-527e43a919bc.png)

**软件硬件信息**
操作系统: [ 如: 安卓10 ]
设备型号: [ 如: 华为mate30 pro ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.1.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by GodManRui** [comment]
+1，我是华为P30 pro，android 10的也是

**Comment by SuperMonster003** [comment]
2 日之内将发布新版本解决上述问题

**Comment by GodManRui** [comment]
> 2 日之内将发布新版本解决上述问题
> […](#)
> On May 18, 2021 10:31:59 GodRUI ***@***.***> wrote: +1，我是华为P30 pro，android 10的也是 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬牛皮，加油

**Comment by Z-L-X** [comment]
@同能量雨报错，日志截图如下
![Screenshot_2021-05-19-10-58-10-740_org autojs autojs](https://user-images.githubusercontent.com/45785519/118750796-c5658e80-b825-11eb-9ace-0476d29830c5.jpg)

**Comment by SuperMonster003** [comment]
@Z-L-X 
近期即将发布的 `v2.1.3` 版本已尝试解决上述问题
使用后如问题复现 可提交新问题反馈
