### ISSUE TITLE
好友列表下拉时经常报错

### ISSUE THREAD

**Issue by xy3217991** [SuperMonster003/Ant-Forest#468]
日志：05:21:53.711/E: Error: out of region: region = [767,1451,302,866], image.size = [2340,1080] (file:///android_asset/modules/__images__.js#523) Error: out of region: region = [767,1451,302,866], image.size = [2340,1080] 
at
buildRegion(file:///android_asset/modules/__images__.js:523:0) 
at file:///android_asset/modules/__images__.js:395:0 at _chkInvtBtn (/storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:6049:0) 
at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-global.js:187:0 
at _swipe (/storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:5937:0)
 at /storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:5153:0 
at 

 /storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:7013:0 
at /storage/emulated/0/脚本/Ant-Forest-003/ant-forest-launcher.js:7065:0

小米10
miui12.5.3稳定版[]()

**Comment by xy3217991** [comment]
#432的方法无效了

**Comment by SuperMonster003** [comment]
这个是横向截图导致的宽高溢出

后续版本将尝试通过代码改变屏幕旋转方向 (accelerometer rotation) 避免上述出现的横向截图问题

可关注后续版本更新
