### ISSUE TITLE
mate 30 pro 5G 鸿蒙2.0 显示语言为英语的时候，无法获取截屏权限

### ISSUE THREAD

**Issue by iciness** [SuperMonster003/Ant-Forest#475]
**问题描述**
显示语言为英语的时候，无法获取截屏权限

**日志截图**
![微信图片_20210603175033](https://user-images.githubusercontent.com/4505686/120625580-71e57880-c494-11eb-9e51-ac0152b6a92c.jpg)
![image](https://user-images.githubusercontent.com/4505686/120626433-3b5c2d80-c495-11eb-967d-30f642824078.png)

**软件硬件信息**
操作系统: [ 鸿蒙2.0 ]
设备型号: [ mate 30 pro 5g ]
Auto.js版本: [ AutoX5.0.1 ]
项目版本: [ v2.12 ]

**Comment by realheyu** [comment]
没看使用说明? 安卓的app, 你哄蒙用个寄吧

**Comment by iciness** [comment]
在英语环境时已经可以获取截屏权限
