### ISSUE TITLE
申请截图权限requestScreenCapture有时会卡住

### ISSUE THREAD

**Issue by tianzhenwuxie01** [SuperMonster003/Ant-Forest#478]
[ 关于项目的疑惑顾虑/心得体会/经验分享等 ]
大佬，autojs在申请截图权限requestScreenCapture()的时候，有时会出现卡住的现象。有啥解决方法吗？
例如可以设置函数超时吗，申请超过指定时间就停止或者重新申请？
跪求大佬解惑！

**Comment by SuperMonster003** [comment]
---
##### 使用注意
---

```
images.requestScreenCapture();
```
上述方法在单次会话中只能使用一次
第二次调用会出现假死

---
##### 避免上述问题
---

设置一个全局标记变量
调用后设置一个标记值
后续调用截图权限申请方法时优先检查标记值
如果已被标记则不再执行权限申请

标记变量可用基本类型值 (如 number 或 boolean 等)
但更推荐使用  java.util.concurrent.atomic.AtomicLong 类型
这样对于多线程调用有更好的兼容性
示例代码如下

```js
imagesx.permit();
threads.start(function () {imagesx.permit()});
threads.start(function () {imagesx.permit()});
threads.start(function () {imagesx.permit()});
threads.start(function () {
    imagesx.permit();
    imagesx.permit();
});
imagesx.permit();
imagesx.permit();
```

如果使用 JavaScript 基本类型
对于上述极端情况将有大概率出现非预期结果

---
##### 使用当前项目已封装的模块方法
---

```js
require('./modules/ext-images').permit();
```
或
```js
require('./modules/ext-images').load();
imagesx.permit();
```
