### ISSUE TITLE
Bug反馈: [ v2.1.2无法自动升级到v2.1.3 ]

### ISSUE THREAD

**Issue by chenyubug** [SuperMonster003/Ant-Forest#479]
**问题描述**
V2.1.2无法自动升级到V2.1.3

**日志截图**
正在部署项目V2.1.3
► 1.下载数据包[407.7 KB ]
2 .解压缩
3 .备份本地项目
4 .项目文件替换
5 .清理并完成部署
请求失败：
JavaException: javax.net.ssl.SSLHa
ndshakeException: SSL handshake
aborted: ssl=0xce5af008: I/O error
during system call, Connection
reset by peer

**软件硬件信息**
操作系统: [安卓9.0 ]
设备型号: [小米6]
Auto.js版本: [4.1.1 Alpha2 ]
项目版本: [ v2.1.2 ]

**Comment by SuperMonster003** [comment]
GitHub 在某些情况下连接不稳定
可再尝试几次 或 更换网络环境 (Wi-Fi / 移动数据 / 虚拟专用网 等)
