### ISSUE TITLE
交流研讨: 部署项目时，一直在获取版本信息。是否有需要注意的操作

### ISSUE THREAD

**Issue by sn5dipone6** [SuperMonster003/Ant-Forest#480]
当我下载源码，并放置在脚本目录下后。直接在运行/storage/emulated/0/脚本/Ant-Forest-2.1.3/tools/ant-forest-deployment-tool.js
时，一直处于获取版本信息界面。长时间不变。这是为什么？

**Comment by SuperMonster003** [comment]
与 #479 类似
GitHub 服务器在国内某些网络环境下容易出现响应超时情况

"正在获取版本信息..."一定时间后 会出现"版本信息获取失败"提示
可尝试重新运行部署工具 (可能需要多次) 或改变设备网络环境

若上述过程发现 Auto.js 日志中存在报错或其他异常
可反馈日志截图或上传日志文件

**Comment by SuperMonster003** [comment]
如果使用的是 Auto.js Pro 版本
则会出现获取版本信息卡住的问题
且日志中会有报错
`v2.1.4` 已尝试修复此问题
