### ISSUE TITLE
Bug反馈: v2.1.3找不到函数getName

### ISSUE THREAD

**Issue by lwh201314** [SuperMonster003/Ant-Forest#481]
**问题描述**
运行的时候提示找不到函数getName

**日志截图**
![Screenshot_2021-06-25-07-09-10-007_org autojs autojspro](https://user-images.githubusercontent.com/33437578/123343972-6e21af00-d585-11eb-9084-5dca7dca0d6d.jpg)

**软件硬件信息**
操作系统:  安卓11 
设备型号: 小米9
Auto.js版本: Pro 8.3.16
项目版本: 2.1.3

**Comment by SuperMonster003** [comment]
已于 `v2.1.4` - `2021/06/25` 尝试修复上述问题
