### ISSUE TITLE
Bug反馈: [ SettingNotFoundException: development_settings_enabled ] (Edited)

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#483]
问题描述
android.provider.Settings$SettingNotFoundException: development_settings_enabled
偶尔，一次收集结束后，会报这个错误，见日志776行
下次任务会无法执行（可能当前任务没有被正确结束，如图所示，进行中的任务会有2个，且是同一个）

日志截图
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6719549/auto.js-log.log)
![Screenshot_20210626_095539](https://user-images.githubusercontent.com/9878167/123501476-ca64fb80-d677-11eb-932b-09545ee9eab2.jpg)

软件硬件信息
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: iQOO5 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]

**Comment by linfeizheng** [comment]
报错的时候不会出现沙漏遮盖的页面
据我观察，定时任务启动前屏幕是黑屏时，任务结束后才会出现这种情况

**Comment by SuperMonster003** [comment]
'2.1.4 - Fix' 已修复上述问题
尝试使用项目部署工具重新部署最新版
或使用配置工具的服务器还原功能还原一下最新版

**Comment by SuperMonster003** [comment]
检查了一下日志
其中存在的问题并非是上述已修复的问题
将在下一版本尝试修复

**Comment by SuperMonster003** [comment]
[ext-device.zip](https://github.com/SuperMonster003/Ant-Forest/files/6720066/ext-device.zip)

将 *.zip 文件解压后得到 ext-device.js 扩展模块
将该模块放置于项目的 modules 文件夹下替换原有文件
尝试再次运行项目 (手动运行 - 推迟一分钟 - 关闭屏幕 - 等待脚本自动运行并观察是否能正常关屏)

**Comment by linfeizheng** [comment]
没有问题了，待我观察两天，谢谢

**Comment by linfeizheng** [comment]
perfect
