### ISSUE TITLE
Bug反馈: 错误码显示：Wrapped java.lang.NulPointerException Attempt to read from nul array (file:ilandroid_asset/ modules _images.ist440)

### ISSUE THREAD

**Issue by loloago** [SuperMonster003/Ant-Forest#484]
**问题描述**
排行榜可以收取，但是用逛一逛就报错误。

**日志截图**
![Uploading Screenshot_20210626_190846_com.eg.android.AlipayGphone.jpg…]()

**软件硬件信息**
操作系统: [ 如: 安卓8.0 ]
设备型号: [ 如: 索尼 G8441 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by loloago** [comment]
Wrapped java.lang.NulPointerException Attempt to read from nul array (file:ilandroid_asset/ modules _images.ist440)

**Comment by SuperMonster003** [comment]
刚运行测试了一下项目
没能复现上述问题
请提供日志图片或日志文件

关于如何上传图片
可参阅 https://github.com/SuperMonster003/Ant-Forest/issues/415#issuecomment-775757968
