### ISSUE TITLE
Bug反馈: [ 无法创建下次任务，提示 "a fruitless attempt" ] (Edited)

### ISSUE THREAD

**Issue by GodManRui** [SuperMonster003/Ant-Forest#485]
**问题描述**
清晰且简明地描述此问题
无法创建下次任务，做完一次后没有下个定时任务了，提示a fruitless attempt
锁屏后也无法唤醒设备
autojs能给的权限都给了，左侧导航栏读取通知权限，前台服务，稳定模式，等等，全都打开了，华为电池优化也对aj关闭了
**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ 如: 安卓8.0 ]  鸿蒙2.0
设备型号: [ 如: 索尼 G8441 ]  mate40Pro 华为
Auto.js版本: [ 如: 4.1.1 Alpha2 ]  4.1.1 Alpha2
项目版本: [ 如: v1.9.1 ] 刚更新过的最新版

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
项目配置工具是否开启了 "定时循环" 功能及 "定时任务自动管理" 子功能

**Comment by GodManRui** [comment]
误会误会，昨晚看了下，定时循环确实关了mmm，现在就是锁屏后AJ无法自动拉起执行定时任务了，请问这个有啥方案吗？

**Comment by GodManRui** [comment]
好啦好啦，打扰啦
