### ISSUE TITLE
Bug反馈: [ SettingNotFoundException: development_settings_enabled ] (Edited)

### ISSUE THREAD

**Issue by GodManRui** [SuperMonster003/Ant-Forest#487]
**问题描述**
清晰且简明地描述此问题
收完能量后，进行到锁屏流程时，抛出异常，导致流程不往下走，当前任务一直卡主结束不了

**日志截图**
提供与问题相关的日志截图
![image](https://user-images.githubusercontent.com/30816530/123586575-814bad80-d817-11eb-95e4-07cfa6a7eb52.png)
![image](https://user-images.githubusercontent.com/30816530/123586607-8c064280-d817-11eb-93ea-69a4400d7aed.png)

**软件硬件信息**
操作系统: [ 如: 安卓8.0 ] 鸿蒙2.0
设备型号: [ 如: 索尼 G8441 ] mate40 pro
Auto.js版本: [ 如: 4.1.1 Alpha2 ]4.1.1 Alpha2
项目版本: [ 如: v1.9.1 ] 最新版本

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]
看报错可能跟鸿蒙系统有关，某些系统方法没有找到？如果能完美修复最好了，修复不了的话，是不是能try catch住，跳过关屏幕的流程呢？现在主要矛盾是当前任务结束不了，会导致下次定时任务无法执行。

**Comment by SuperMonster003** [comment]
先参照 https://github.com/SuperMonster003/Ant-Forest/issues/483 覆盖一下文件吧
下一版本将正式修复上述问题

**Comment by GodManRui** [comment]
好的，谢谢，我试试
