### ISSUE TITLE
Bug反馈: [ 能量雨工具报错: img is required for imagesx._buildRegion()... ] (Edited)

### ISSUE THREAD

**Issue by xy3217991** [SuperMonster003/Ant-Forest#488]
**问题描述**
能量雨还是有问题
**日志截图**
![IMG_20210630_073613](https://user-images.githubusercontent.com/61336326/123884690-6cd5f500-d97e-11eb-9d00-735c76270f49.jpg)

**软件硬件信息**
操作系统: [MIUI 12.5.3 ]
设备型号: [小米10]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.1.4 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]
![IMG_20210630_073613](https://user-images.githubusercontent.com/61336326/123884668-5a5bbb80-d97e-11eb-8cf5-c6dc3bf6024f.jpg)

**Comment by SuperMonster003** [comment]
已于 `v2.1.5` - `2021/06/30` 尝试修复上述问题
另外 https://github.com/SuperMonster003/Ant-Forest/issues/468 的问题是否复现 ?

**Comment by xy3217991** [comment]
你好，#468 问题未复现😀
