### ISSUE TITLE
执行任务前，手机在横屏看视频，就无法启动任务

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#489]
问题描述
执行任务前，我在爱奇艺APP看视频，是全屏的，任务启动倒计时结束后，跳转到蚂蚁森林，会报错
见日志文件 11点47分（最下面）

日志截图
![Screenshot_20210630_114727](https://user-images.githubusercontent.com/9878167/123899174-42456580-d999-11eb-909f-a113e14e92da.jpg)
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6737886/auto.js-log.log)

软件硬件信息
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: iQOO5 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]

**Comment by SuperMonster003** [comment]
已于 `v2.1.5` - `2021/06/30` 尝试修复上述问题
