### ISSUE TITLE
没有按时收取自己能量，任务在7点半之前结束

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#492]
问题描述
2个问题
1.我的行走能量是7:14成熟，但是7:17才收
2.能量偷到7:19后就没再偷了，显示下次执行时间是08:13显然也是不对的，因为7点半前还有很多好友没有去偷

日志截图
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6744952/auto.js-log.log)

软件硬件信息
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: iQOO5 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]

**Comment by SuperMonster003** [comment]
参照 issue #491  尝试应用一下最新补丁

**Comment by weiouyang** [comment]
> 问题描述
> 2个问题
> 1.我的行走能量是7:14成熟，但是7:17才收
> 2.能量偷到7:19后就没再偷了，显示下次执行时间是08:13显然也是不对的，因为7点半前还有很多好友没有去偷
> 
> 日志截图
> [auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6744952/auto.js-log.log)
> 
> 软件硬件信息
> 操作系统: [ 如: 安卓10.0 ]
> 设备型号: [ 如: iQOO5 ]
> Auto.js版本: [ 如: 4.1.1 Alpha2 ]

我的都不会自动启动偷呜呜呜，每次都要手动打开无障碍，你们知不知道咋自动打开无障碍鸭

**Comment by linfeizheng** [comment]
我昨天使用了方法1重新部署了项目，今早还是有问题
7:21任务结束，7:29又开始，期间有很多好友能量未收
截图与日志敬上
![Screenshot_20210702_111129](https://user-images.githubusercontent.com/9878167/124215296-54084380-db26-11eb-842d-eb44ac42f2a5.jpg)
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6751819/auto.js-log.log)

**Comment by SuperMonster003** [comment]
因为7点21分 Auto.js 崩溃了
体现在日志中就是 07:21:33.746 出现的断档

与修复前的问题不同
之前的问题是获取倒计时一直都是 1 项
因为 $$sel.pickup() 内部逻辑除了问题

7 月 2 号的日志文件可以看到
类似 "捕获好友能量倒计时数据: xx项" 这样的日志
xx 都是大于 1 的
说明非修复前的问题并没有复现

至于如何防止 AJ 崩溃
目前暂时没有能通过代码实现的解决方案
因为除了手机限制了 Auto.js 的后台运行外
更多的可能还是项目代码或 Auto.js 软件本身的缺陷

**Comment by linfeizheng** [comment]
没办法就算了，谢谢
