### ISSUE TITLE
点击遗漏和逛一逛遗漏问题

### ISSUE THREAD

**Issue by ljaist** [SuperMonster003/Ant-Forest#495]
1.有多个能量球或能量球位于最边缘时常常点击不到，要怎么修改配置？
2.我好友较多，逛一逛提示没有能量了，但是在反复点击逛一逛又会发现能量，这可能是官方自己的获取不完整造成。所以我需要反复多点几次逛一逛直到比如连续的5次都提示没有能量了，我的列表里才可能真的没有能量了。
3.另，有时候森林会出现系统繁忙，请稍后字幕提示，然后就手工也暂时无法收取能量了。怀疑是使用能量雨或者逛一逛点击过于快速导致。

**Comment by SuperMonster003** [comment]
> 1.有多个能量球或能量球位于最边缘时常常点击不到，要怎么修改配置？
这个暂时没有提供参数配置选项
以后可能会考虑开发 但开发难度较大 尤其是可视化方面
目前暂时不会做代码变更 除非有热心用户提供更好的参数配置方案
> 2.我好友较多，逛一逛提示没有能量了，但是在反复点击逛一逛又会发现能量...
目前无法解决
因为逛一逛按钮点击后 项目是无法做干预和结果预判的
详见配置工具中有关逛一逛方案的利弊简介
> 3.另，有时候森林会出现系统繁忙，请稍后字幕提示，然后就手工也暂时无法收取能量了...
设备是否 root
是否开启并使用过相关的框架模块
