### ISSUE TITLE
保护罩页面停留久

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#496]
问题描述
保护罩换样式了，貌似无法识别了，会在有保护罩的页面停留挺久

日志截图
暂时先不导出了，有需要我再导出

软件硬件信息
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: iQOO5 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]

**Comment by SuperMonster003** [comment]
是猫形保护罩吗
那个应该是活动日才有的且每人最多只有一个
暂时不考虑做额外适配或兼容性增强
除非后续有其他异形保护罩高频出现

此 issue 将标记为 '无法完成'

**Comment by linfeizheng** [comment]
原来如此
