### ISSUE TITLE
Bug反馈: [ “好友排行榜”初始状态准备失败 ]

### ISSUE THREAD

**Issue by hsw0630** [SuperMonster003/Ant-Forest#498]
**问题描述**
大概是又改了了样式，今天开始出现这个问题

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ 如: 安卓11]
设备型号: [ 如: 小米9PRO]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.1.5 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by hsw0630** [comment]
> **问题描述**
> 大概是又改了了样式，今天开始出现这个问题
> 
> **日志截图**
> 
![Screenshot_2021-07-15-18-17-58-655_org autojs autojs](https://user-images.githubusercontent.com/35106174/125816915-7ee4e452-1c8d-4436-9a83-7b039a035280.jpg)

> 
> **软件硬件信息**
> 操作系统: [ 如: 安卓11]
> 设备型号: [ 如: 小米9PRO]
> Auto.js版本: [ 如: 4.1.1 Alpha2 ]
> 项目版本: [ 如: v2.1.5 ]
> 
> **其他**
> [ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Ant-Forest/blob/943c02af44ef101bffc7e596a1c4b7e8dc59b49b/ant-forest-launcher.js#L1860
可尝试在启动器脚本1860行之后插入以下代码
```js
readTitle: 'NO',
```

**Comment by hsw0630** [comment]
> https://github.com/SuperMonster003/Ant-Forest/blob/943c02af44ef101bffc7e596a1c4b7e8dc59b49b/ant-forest-launcher.js#L1860
> 
> 
> 可尝试在启动器脚本1860行之后插入以下代码
> ```js
> readTitle: 'NO',
> ```

试了下，可以，感谢大佬

**Comment by NonoKing** [comment]
我也是这个问题，我去试试看

**Comment by tygwd** [comment]
同样的问题，已经完美解决，感谢大佬

**Comment by SuperMonster003** [comment]
[v2.1.6](https://github.com/SuperMonster003/Ant-Forest/releases/tag/v2.1.6) 已尝试修复上述问题
如问题复现 可继续反馈
