### ISSUE TITLE
Bug反馈: [ 扫描好友排行榜到底部无法结束 ]

### ISSUE THREAD

**Issue by NonoKing** [SuperMonster003/Ant-Forest#499]
**问题描述**
逛一逛结束之后，扫描排行榜，到了最底部，一直卡在这里无法结束，只能强制退出

**日志截图**
![image](https://user-images.githubusercontent.com/33653932/126022993-d3f3acd1-4d92-45a5-83e1-6e26638f29f0.png)

**软件硬件信息**
操作系统: 安卓10；MIUI12.0.3
设备型号: Redmi Note 7
Auto.js版本: 4.1.1 Alpha2
项目版本: v2.1.5

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
将在下一版本尝试解决上述问题
下一版将于 Jul 23, 2021 前发布

目前可尝试将排行榜样本采集策略切换为排行榜策略
或临时关闭项目的定时循环功能

**Comment by SuperMonster003** [comment]
[v2.1.6](https://github.com/SuperMonster003/Ant-Forest/releases/tag/v2.1.6) 已尝试修复上述问题
如问题复现 可继续反馈

**Comment by NonoKing** [comment]
> [v2.1.6](https://github.com/SuperMonster003/Ant-Forest/releases/tag/v2.1.6) 已尝试修复上述问题
> 如问题复现 可继续反馈

已更新到最新版，问题没有出现了
