### ISSUE TITLE
Bug反馈: [不能自动锁屏，不能自动解锁]

### ISSUE THREAD

**Issue by twanghey** [SuperMonster003/Ant-Forest#501]
**问题描述**
锁屏与解锁都不能运作
**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ magic4.0.0]
设备型号: [ 荣耀magic2 ]
Auto.js版本: [  4.1.1 Alpha2 ]
项目版本: [ 2.1.6 ]

**其他**
上一版本还可以自动运行

**Comment by SuperMonster003** [comment]
请提供与问题相关的日志截图或日志文件  
日志文件位于项目目录下的 log 文件夹内(需在配置工具中开启本地日志功能)
