### ISSUE TITLE
MIUI深色模式导致能量识别不到

### ISSUE THREAD

**Issue by fan0629** [SuperMonster003/Ant-Forest#503]
**问题描述**
手机有设置定时深色模式，开启深色模式时无法收取能量。
**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: 安卓11，MIUI12.5
设备型号: 红米k20 pro
Auto.js版本: 4.1.1 Alpha2
项目版本: 2.1.6

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by xzhlksh** [comment]
感觉有点偶发性，可能把颜色阈值调高一点就可以？

**Comment by SuperMonster003** [comment]
项目暂时不对非安卓官方方案的色彩模式做适配  安卓官方的暗色模式 (dark mode) 及 颜色反转 (invert colors) 均不会对 API 产生影响  
但部分定制系统的深色模式或护眼模式等均会影响颜色相关的 API
此 issue 将标记为 "无法完成"

**Comment by xzhlksh** [comment]
这个有办法判断当前是否深色模式么？我知道的是MIUI的深色模式下，如果手动调高亮度的话，脚本还是可以继续正常识别；如果亮度最低就不行了。
所以这种提亮度再运行是不是一种解决方案？
