### ISSUE TITLE
Bug反馈: [ 触发“通话状态”事件 ]

### ISSUE THREAD

**Issue by wxk123** [SuperMonster003/Ant-Forest#504]
**问题描述**
一运行就提示触发通话状态事件，没法用

**软件硬件信息**
操作系统: [  安卓9]
设备型号: [魅族 16s pro ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ 2.1.6 ]

**Comment by SuperMonster003** [comment]
配置工具 - 运行与安全 - 通话状态监测 [关闭]

**Comment by wxk123** [comment]
感谢，完美解决
