### ISSUE TITLE
Bug反馈: [ 逛一逛（收能量）功能出错 ]

### ISSUE THREAD

**Issue by jobinli** [SuperMonster003/Ant-Forest#506]
**问题描述**
采集策略改为逛一逛按钮，执行之后报错无法找到__image__.js

**日志截图**
![375f23a6e8edb1fb6b1d9ec2bed1236](https://user-images.githubusercontent.com/59111601/127092849-50eba195-a4e2-4a55-9ab0-db046d16050b.jpg)

**软件硬件信息**
操作系统: [ 安卓11 ] 
设备型号: [ 红米K40 ]
Auto.js版本: [ Pro 8.8.10-0 ]
项目版本: [ 如: v2.1.6 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
可以先尝试更新Pro至最新版 后期我会根据日志中的信息栈排查代码问题
