### ISSUE TITLE
倒计时弹窗的倒计时无法正常计时

### ISSUE THREAD

**Issue by linfeizheng** [SuperMonster003/Ant-Forest#507]
问题描述
偶尔我的脚本会出现这种情况，倒计时弹窗出现时，会有倒计时x秒的提示，如图一，但是马上，就变成图二，不开始倒计时了
附上今天上午7点多的日志，每5分钟出现一次这种情况

日志截图
![Screenshot_20210727_142713](https://user-images.githubusercontent.com/9878167/127107949-82b13f2a-eed8-4596-8240-cca9bc71622b.jpg)
![Screenshot_20210727_142716](https://user-images.githubusercontent.com/9878167/127107943-0ac7bc63-fb33-4f9e-bf23-428266d6c72b.jpg)
[auto.js-log.log](https://github.com/SuperMonster003/Ant-Forest/files/6883241/auto.js-log.log)

软件硬件信息
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: iQOO5 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]

**Comment by SuperMonster003** [comment]
目前暂无解决方案  
可尝试重新启动设备或 Auto.js 解决上述问题  
另 v2.1.7 加入的内存信息工具可直接重启 Auto.js 进程 (可替代无 root 权限状态下的 Auto.js 重启操作)
