### ISSUE TITLE
Bug反馈: [ 此处简述问题概要 ] 找不到方法，能力保护罩必现

### ISSUE THREAD

**Issue by GodManRui** [SuperMonster003/Ant-Forest#511]
**问题描述**
清晰且简明地描述此问题
碰到有能量bao保护罩的好友必现，停止运行了就。 最新2.1.7版本
**日志截图**
提供与问题相关的日志截图
![image](https://user-images.githubusercontent.com/30816530/128863305-832b4574-4c56-4e74-bb17-5922891ee219.png)

**软件硬件信息**
操作系统: [ 如: 安卓8.0 ]
设备型号: [ 如: 索尼 G8441 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
参阅 #491

**Comment by GodManRui** [comment]
新版本settting内点最后一个关于脚本及开发者时报错，
![image](https://user-images.githubusercontent.com/30816530/128959726-dfbc1135-a520-4c14-8c40-4764a048a4a3.png)

**Comment by SuperMonster003** [comment]
新版本已尝试修复配置工具对话框相关的问题  
如更新使用后问题复现 可继续反馈

**Comment by GodManRui** [comment]
嗯新版本不会了！
