### ISSUE TITLE
自动解锁设置密码或设置最大重试次数无效,在设置界面仍显示"无"和"20",且定时运行时若处于锁屏状态无法自动解锁

### ISSUE THREAD

**Issue by Jamie502** [SuperMonster003/Ant-Forest#513]
**问题描述**
自动解锁设置密码或设置最大重试次数无效,在设置界面仍显示"无"和"20",且定时运行时若处于锁屏状态无法自动解锁进行草最

![Uploading Screenshot_20210812_161853_org.autojs.autojs.jpg…]()

**日志截图**
![Uploading Screenshot_20210812_161750_org.autojs.autojs.jpg…]()

**软件硬件信息**
操作系统: 鸿蒙2.0.0.145
设备型号: 荣耀30pro EBG-AN00
Auto.js版本:  4.1.1 Alpha2
项目版本:v2.1.7

请问作者大大是哪里出了问题呀,是我操作不对么

**Comment by SuperMonster003** [comment]
今晚或明晚发布 v2.1.8 将修复上述问题  
请关注后续版本更新  
另外 v2.1.7 存在的问题可能无法使用配置工具更新项目版本 如无法使用 可尝试使用项目部署工具完成更新

**Comment by Jamie502** [comment]
> 今晚或明晚发布 v2.1.8 将修复上述问题
> 请关注后续版本更新
> 另外 v2.1.7 存在的问题可能导致无法使用配置工具更新项目 可尝试使用项目部署工具完成更新
多谢作者大大，已解决

**Comment by Jamie502** [comment]
感谢作者大大,已解决
