### ISSUE TITLE
2.1.7和2.1.8加入闹钟检测后出现问题

### ISSUE THREAD

**Issue by zhu086** [SuperMonster003/Ant-Forest#514]
**问题描述**
所有闹钟都关掉

**日志截图**
![Uploading Screenshot_20210815_105118_org.autojs.autojs.jpg…]()

**软件硬件信息**
操作系统: [ 华为鸿蒙]
设备型号: [ p30p]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.7.1,1.8.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
请提供详细的问题描述  
是闹钟时间一到立即就被脚本点击了还是闹钟界面没有出现  
另外建议运行配置工具 勾选消息提示功能下的开发者测试模式 然后设置一个临近闹钟 运行项目并让项目出现闹钟倒计时 然后提供一下日志截图  
另外最好能提供运行过程的录屏或录像
