### ISSUE TITLE
2.1.7和2.1.8加入闹钟检测后出现问题

### ISSUE THREAD

**Issue by zhu086** [SuperMonster003/Ant-Forest#515]
**问题描述**
所有闹钟都关掉

**日志截图**

![Screenshot_20210815_105118_org autojs autojs](https://user-images.githubusercontent.com/67412456/129465947-d6ae1520-2851-486c-b023-435e40309b2e.jpg)
![Screenshot_20210815_104928_com eg android AlipayG](https://user-images.githubusercontent.com/67412456/129465949-3b950c5b-f238-4857-8d9a-3f5fd3134dfd.jpg)

**软件硬件信息**
操作系统: [ 华为鸿蒙]
设备型号: [ p30p]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.7.1,1.8.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by zhu086** [comment]
![Uploading Screenshot_20210815_105118_org.autojs.autojs.jpg…]()

**Comment by SuperMonster003** [comment]
请提供详细的问题描述
是闹钟时间一到立即就被脚本点击了还是闹钟界面没有出现
另外建议运行配置工具 勾选消息提示功能下的开发者测试模式 然后设置一个临近闹钟 运行项目并让项目出现闹钟倒计时 然后提供一下日志截图
另外最好能提供运行过程的录屏或录像

**Comment by zhu086** [comment]
所有闹钟关掉，运行，提示，闹钟即将在x秒內触发，然后运行结束。

刚才设置一个闹钟，在闹钟时间要到的前10秒，运行脚本，居然一切正常了，

问题已解决，感谢
