### ISSUE TITLE
Bug反馈: [ v2.2.2 MIUI 13 能量雨无法识别与收取 ]

### ISSUE THREAD

**Issue by PRSJMC** [SuperMonster003/Ant-Forest#555]
**问题描述**
收取模式 列表 和 逛一逛 都试过了，前者不弹能量雨界面，后者弹了后自动结束，从日志上看不出什么报错。

**日志截图**
![image](https://user-images.githubusercontent.com/46528990/157367841-bb00f90c-9375-41e1-9c79-e4852ae1be73.png)
![image](https://user-images.githubusercontent.com/46528990/157368004-3efd9d73-ff11-4435-8de9-5922761e5865.png)

**软件硬件信息**
操作系统: [ 如: MIUI 13]
设备型号: [ 如: Redmi K30S ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.2.2 ]

**其他**
[ 另外想问问这个延时接力功能哪里可以关掉，每天收一次对我就足够了； ]

**Comment by GodManRui** [comment]
MIUI13自己的bug，升级miui13更新补丁就行了

**Comment by PRSJMC** [comment]
> MIUI13自己的bug，升级miui13更新补丁就行了

请问是升级到哪个版本呢？目前还待在稳定版13.0.4

**Comment by SuperMonster003** [comment]
项目目前没有收集能量过程中自动收集能量雨的功能
只能手动运行能量雨脚本进行能量雨收集
脚本位于 项目主目录/tools/energy-rain-harvesting.js

延时接力功能可在运行项目配置工具 (ant-forest-settings.js) 后
在 定时循环/定时任务自动管理 页面设置

**Comment by PRSJMC** [comment]
> 项目目前没有收集能量过程中自动收集能量雨的功能 只能手动运行能量雨脚本进行能量雨收集 脚本位于 项目主目录/tools/energy-rain-harvesting.js
> 
> 延时接力功能可在运行项目配置工具 (ant-forest-settings.js) 后 在 定时循环/定时任务自动管理 页面设置

感谢作者的回复，实测手动运行能量雨没问题的，如果能自动化运行就再好不过了。
另外对于能量雨，希望能考虑增加一个功能：每天自动赠送机会给好友（默认第一位就行）。
延时接力功能已测试可以关闭。
