### ISSUE TITLE
Bug反馈: [ v2.2.2 Auto.js 6.0.2 无法解锁屏幕]

### ISSUE THREAD

**Issue by PRSJMC** [SuperMonster003/Ant-Forest#557]
**问题描述**
首先十分感谢作者的脚本，最近看到公告后去安装了里面提及的Auto.js 6.0.2版本。
但定时解锁功能在上滑的时候一直无法进入到密码输入的界面，（上滑设置为默认设置）日志如下。

**日志截图**
![1647129812415](https://user-images.githubusercontent.com/46528990/158039286-53b29ef3-99eb-4eb0-9ed9-e889bebb806c.jpg)

**软件硬件信息**
操作系统: [ 如: MIUI13 安卓12]
设备型号: [ 如: Redmi K30S]
Auto.js版本: [ 如: 6.0.2 ]
项目版本: [ 如: v2.2.2 ]

**其他**
[原来用的一个修改版是正常的，看它的权限里面有一项闹钟和提醒，这点是和6.0.2不同的，其版本如下
![image](https://user-images.githubusercontent.com/46528990/158039333-5b4fe079-bd45-4a20-8896-3e257204d8c4.png)
 ]

**Comment by fflzh** [comment]
我原先用的4.1.1版本，然后也是今天看到公告，改成了6.0.2版本，然后我的能解锁，但是关闭不了屏幕，提示关屏策略执行失败，需要“修改系统设置”权限

**Comment by PRSJMC** [comment]
我重新复现了下，“修改系统设置”权限开着，依旧是上图的报错。（解锁设置相关的设置都改为默认了）

**Comment by dreamflandre** [comment]
尝试修改自动解锁-上滑时长，我也遇到此问题，修改上滑时长竖直更大后就可以解锁了

**Comment by PRSJMC** [comment]
> 

谢谢！设置为500ms后可以了。
